// German help content: same topics, tasks and step counts as HELP in help.js. Button and menu names are quoted as the
// German interface shows them – translated where the app translates them, otherwise in English as on screen.
const ADMIN='Plattform-Admin';
export const HELP_DE={
  start:{title:'Erste Schritte',what:'Die Reihenfolge für die Einrichtung – vom leeren System bis zu laufenden Maschinen, Kameras und Rückverfolgung.',
    tasks:[
      ['Ersteinrichtung (Plattform-Admin)',[
        'Mit dem bei der Installation angelegten Admin-Konto anmelden und unter <b>Mein Konto</b> das Passwort ändern.',
        '<b>Administration › Firmen, Werke & Benutzer</b>: jede Kundenfirma anlegen, dann ihre Werke (Adresse, Servicegebiet, Schichtmodell).',
        'Bei jedem Werk <b>Edit shifts</b> verwenden: OEE, Energie und Alarme werden nur innerhalb der geplanten Schichtzeit gemessen.',
        'Benutzer mit <b>Add user</b> anlegen. Die Rolle sorgfältig wählen (siehe <i>Rollen</i> unten) und ein vorläufiges Passwort vergeben; es muss bei der ersten Anmeldung geändert werden.',
        '<b>Administration › Einstellungen</b>: Codelisten, Servicegebiete, Standard-Checklisten, Standard-Reaktionszeiten und die Scan-Regel prüfen.',
        '<b>Maintenance › Anlagenverzeichnis</b>: jede Maschine, jedes Werkzeug und jedes Peripheriegerät mit Inventarnummer erfassen.',
        '<b>Production › Produkte & Zykluszeiten</b>: die gefertigten Teile mit idealer Zykluszeit und Kavitäten anlegen, damit die OEE-Leistung berechnet werden kann.',
        'Maschinendaten anbinden: einen Maschinendatensatz öffnen, <b>Connect IoT device</b> wählen und dann <b>Administration › Maschinendaten (IoT)</b> prüfen.',
        'Optional: <b>Maintenance › Wartungsverträge</b> und <b>Administration › Servicepartner</b> für externe Servicepartner.',
        'Optional für Vision: Lizenzen und Edge-Knoten unter <b>Vision › Edge-Knoten & Lizenzen</b> anlegen, dann Kameras und Module unter <b>Kameras & KI-Module</b>.']],
      ['Rollen',[
        '<b>Plattform-Admin</b>: alles, einschließlich Lizenzen, Einstellungen und Servicepartnern.',
        '<b>Disposition</b>: weist Störmeldungen für alle Kunden zu und steuert sie; sieht Fertigungs- und Vision-Seiten.',
        '<b>Servicetechniker</b>: bearbeitet die ihm zugewiesenen Störmeldungen.',
        '<b>Kunden-Admin</b>: verwaltet die eigene Firma: Werke, Benutzer, Anlagen, Kameras, Verträge.',
        '<b>Werksleitung</b>: steuert die Fertigung der eigenen Firma: Schichten, Produkte, Grenzwerte, Chargenfreigabe, Entscheidungen.',
        '<b>Instandhaltung</b>: meldet und verfolgt Störungen, erfasst Fertigungsdaten.',
        '<b>Partner-Admin / Partner-Techniker</b>: ein externer Partner; bearbeitet Störmeldungen und Angebote, die seiner Firma zugewiesen sind.']]],
    tips:['Auf jeder Seite öffnet die Taste <b>?</b> die Hilfe zu dieser Seite.','Fehlt ein Menüpunkt, hat Ihre Rolle meist keinen Zugriff – wenden Sie sich an Ihren Administrator.']},

  // ---------- Fertigung (IMM) ----------
  floor:{what:'Eine Live-Kachel je Fertigungsmaschine: läuft, wartet, steht oder ausgefallen – mit aktuellem Teil, Ausbringung und OEE der Schicht.',who:'Kundenrollen, Disposition und Plattform-Admins.',
    tasks:[['Ein Werk beobachten',['Oben das Werk auswählen. Die Seite aktualisiert sich selbst.','Auf einer Kachel <b>Machine record</b> für die Maschinendaten oder <b>OEE history</b> für den Verlauf anklicken.']]],
    tips:['Eine Maschine ohne Daten wird als veraltet angezeigt: ihre IoT-Geräteanbindung unter <b>Maschinendaten (IoT)</b> prüfen.']},
  oee:{what:'Gesamtanlageneffektivität = Verfügbarkeit × Leistung × Qualität, gemessen nur innerhalb der geplanten Schichtzeit.',who:'Kundenrollen, Disposition und Plattform-Admins.',
    tasks:[['OEE auswerten',['Oben mit den Filtern Werk, Maschine und Zeitraum wählen.','Das Verlaufsdiagramm lesen, dann die Tabelle <b>By machine</b> mit Verfügbarkeit, Leistung, Qualität, Gut- und Ausschussteilen und Stillstandszeit.']]],
    tips:['Die Leistung braucht die richtige ideale Zykluszeit und die Kavitäten unter <b>Produkte & Zykluszeiten</b>.','Ohne Schichten im Werk gibt es keine geplante Zeit, und die OEE bleibt leer: unter <b>Firmen, Werke & Benutzer › Edit shifts</b> festlegen.']},
  products:{what:'Die gespritzten Teile und ihre ideale Taktung, an der die OEE-Leistung gemessen wird.',who:'Kunden-Admins, Werksleitung und Plattform-Admins können anlegen und bearbeiten; alle anderen lesen.',
    tasks:[['Ein Produkt anlegen',['<b>Add product</b> anklicken.','Kunde, Teilenummer, Name, Material, Teilegewicht und die Zähleinheit der Ausbringung eintragen.','Ideale Zykluszeit und Kavitäten eingeben – die ideale Ausbringung wird daraus berechnet.','Optional das Werkzeug und die übliche Maschine wählen, dann speichern.']],
      ['Ein Produkt ändern',['In der Zeile <b>Bearbeiten</b> anklicken, die Werte ändern und speichern. Neue Werte gelten ab jetzt.']]]},
  alerts:{what:'Probleme, die Maschinenüberwachung und andere Module erkannt haben: Zustandsgrenzwerte, Stillstände, Qualität und Sicherheit.',who:'Kundenrollen, Disposition und Plattform-Admins.',
    tasks:[['Einen Alarm bearbeiten',['Bei einer langen Liste nach Schweregrad, Status oder Quelle filtern.','<b>Acknowledge alert</b> zeigt, dass sich jemand darum kümmert.','<b>Report breakdown</b> macht daraus eine Störmeldung (ohne Scan), oder <b>Open breakdown ticket</b>, wenn es schon eine gibt.','<b>Mark resolved</b>, sobald die Ursache behoben ist.']],
      ['Kritische Alarme per E-Mail erhalten',['Kritische Alarme gehen per E-Mail an Admins, Werksleitung und Instandhaltung des Kunden sowie an die Disposition.','Der Server braucht EMAIL_PROVIDER (brevo, sendgrid oder resend), EMAIL_API_KEY und EMAIL_FROM. Bis dahin warten die E-Mails unter <b>Email notifications</b> als „not configured“.']]],
    tips:['Die Glocke oben rechts zeigt auf jeder Seite die offenen kritischen Alarme und Warnungen.']},

  // ---------- Vision ----------
  vision:{what:'PPE-Einhaltung, Feuer und Rauch, Eindringen in Sperrbereiche und Qualitätsprüfung über alle Kameras – live, mit den offenen Alarmen.',who:'Kundenrollen, Disposition und Plattform-Admins. Welche Alarme Sie sehen, hängt von Ihren Vision-Zuständigkeiten ab.',
    tasks:[['Auf einen Alarm reagieren',['Offene Alarme stehen oben. <b>Acknowledge</b> anklicken, damit andere sehen, dass er bearbeitet wird.','Über <b>All incidents</b> den Nachweis öffnen und den Vorfall abschließen.']],
      ['Festlegen, welche Alarme Sie erhalten',['Ein Admin legt Ihre Zuständigkeiten unter <b>Firmen, Werke & Benutzer › Users › Vision duties</b> fest: EHS (PPE, Feuer/Rauch), Sicherheit (Eindringen) oder QA (Qualität).']]]},
  quality:{what:'Ergebnisse der Kameraprüfung: Erstdurchlaufquote (FPY), Ausschuss in PPM und Fehler-Pareto.',who:'Kundenrollen, Disposition und Plattform-Admins.',
    tasks:[['Die Hauptfehler finden',['Zeitraum und Maschine wählen, dann das Pareto lesen: Bei den ersten Balken lohnt sich die Abhilfe am meisten.','Mit <b>By machine</b> die Linien vergleichen.']]]},
  visionIncidents:{what:'Jede Erkennung mit Foto und 10-Sekunden-Clip – Nachweis des Verstoßes und Prüfprotokoll.',who:'Kundenrollen, Disposition und Plattform-Admins.',
    tasks:[['Einen Vorfall abschließen',['Nach Typ, Kamera, Status oder Datum filtern und den Vorfall öffnen.','Foto und Clip prüfen, dann <b>Resolve</b> (mit Notiz) oder <b>False alarm</b> wählen.','Bei einem Maschinenproblem erzeugt <b>Report breakdown on this machine</b> eine Störmeldung.']],
      ['Nachweise behalten',['<b>Lock evidence</b> schützt Foto und Clip vor der automatischen Löschung. <b>Unlock evidence</b> hebt das wieder auf.']],
      ['Exportieren',['Mit <b>⬇ Export CSV</b> im Seitenkopf die gefilterte Liste herunterladen.']]]},
  visionCameras:{what:'Alle Kameras, der Edge-Knoten, der sie verarbeitet, und die KI-Module, die darauf laufen.',who:'Kunden-Admins (eigene Firma) und Plattform-Admins können ändern; alle anderen lesen.',
    tasks:[['Eine Kamera hinzufügen',['Zuerst muss ein Edge-Knoten existieren (<b>Edge-Knoten & Lizenzen</b>).','<b>Add camera</b> anklicken: Name, Werk, Standort, Edge-Knoten, Kamerahersteller und Verbindungsart.','Die Adresse (z. B. rtsp://user:pass@192.168.0.20/stream) und die Bildrate eingeben, dann speichern.']],
      ['Ein KI-Modul auf einer Kamera ausführen',['Die Firma braucht eine gültige Lizenz für das Modul mit einem freien Platz.','Bei der Kamera <b>+ Add module</b> anklicken, das Modul wählen und <b>Next</b> drücken – oder eine Modulkarte aus <b>AI modules</b> auf die Kamera ziehen.','Die Optionen einstellen (z. B. erforderliche PSA, Empfindlichkeit, Prüfvorlage), <b>Running on this camera</b> angehakt lassen und <b>Add module</b> anklicken.']],
      ['Zonen zeichnen',['<b>Draw zones</b> anklicken, die Eckpunkte des Bereichs im Kamerabild anklicken, Namen, Art und Schweregrad wählen, dann <b>Save zone</b>.']],
      ['Fehler: „No valid … licence for this company“',['Nur ein Plattform-Admin kann Lizenzen anlegen: <b>Edge-Knoten & Lizenzen › Module licences › Edit</b>, Anzahl der Kameras und ein Gültig-bis-Datum festlegen.']],
      ['Fehler: „All N … licences are in use“',['Das Modul von einer anderen Kamera entfernen oder den Plattform-Admin bitten, die Kameraanzahl zu erhöhen.']]]},
  visionNodes:{what:'Die GPU-PCs vor Ort, die Ihre Kamerastreams auswerten, und die KI-Module, für die Ihre Firma lizenziert ist.',who:'Kunden-Admins und Plattform-Admins verwalten Knoten; nur der Plattform-Admin bearbeitet Lizenzen.',
    tasks:[['Eine Lizenz anlegen ('+ADMIN+')',['Unter <b>Module licences</b> in der Zeile der Firma <b>Edit</b> anklicken.','Für jedes Modul festlegen, auf wie vielen Kameras es laufen darf, und bei Bedarf ein Gültig-bis-Datum. Speichern.','Die Knoten übernehmen die Änderung innerhalb von etwa einer Minute.']],
      ['Einen Edge-Knoten hinzufügen',['<b>Add edge node</b> anklicken: Name, Werk, Hardware und wie viele Kamerastreams er verarbeiten kann.','Den einmalig angezeigten Schlüssel kopieren und im Edge-Agent auf diesem PC eintragen. Verloren? <b>New key</b> verwenden – der alte Schlüssel wird ungültig.','Mit <b>View config</b> genau sehen, was der Knoten ausführen wird.']]],
    tips:['Eine Lizenz zeigt <b>Expired</b>, sobald ihr Gültig-bis-Datum überschritten ist; Kameras über die Lizenz hinaus führen das Modul nicht mehr aus.']},

  // ---------- Rückverfolgung ----------
  traceHub:{what:'Jeden Code suchen – Charge, Los, Etikett, Seriennummer, Lieferung oder Rückläufer – und ihn vom Rohmaterial bis zum Kunden und zurück verfolgen.',who:'Kundenrollen, Disposition und Plattform-Admins.',
    tasks:[['Etwas rückverfolgen',['Den Code unter <b>Find anything</b> eingeben oder scannen und <b>Trace</b> drücken.','Im Ergebnis <b>Batch quality & labels</b> oder den Rückrufumfang der Charge bzw. des Loses öffnen.']],
      ['Rückrufumfang',['<b>Recall scope of this lot</b> listet jede Charge, in die das Los eingegangen ist, und wohin diese Teile geliefert wurden.']]]},
  trace:{what:'Materiallose → Chargen → Ausbringung, für schnelle und gezielte Rückrufe.',who:'Kundenrollen und Plattform-Admins erfassen; Werksleitung und Admins geben frei, sperren oder stellen unter Quarantäne.',
    tasks:[['Ein Materiallos erfassen',['<b>Register material lot</b> anklicken: Losnummer, Material, Lieferant, Eingangsdatum, Menge und Zeugnis (CoA / 3.1).']],
      ['Eine Charge fertigen',['<b>Start batch</b> anklicken: Produkt, Maschine, Werkzeug, Chargennummer, Bediener und geplante Menge.','Die in den Trichter oder die Dosiereinheit geladenen Lose erfassen.','Am Ende <b>Complete batch</b> mit Gutmenge und Ausschuss.']],
      ['Freigeben oder stoppen',['<b>Release batch</b> gibt sie zum Versand frei, <b>Put batch on hold</b> sperrt oder verschrottet sie mit Begründung.','Ein verdächtiges Los: <b>Quarantine lot</b>; <b>Release lot</b> hebt das wieder auf.']]]},
  processControl:{what:'Prozessfenster je Produkt, laufende Abweichungen und Prozessfähigkeit (SPC).',who:'Kundenrollen, Disposition und Plattform-Admins; Werksleitung und Admins entscheiden und bearbeiten Regeln.',
    tasks:[['Regeln für ein Produkt festlegen',['Beim Produkt <b>Edit rules</b> anklicken: Kunde, Garantie, Menge pro Karton und was passiert, wenn ein Messwert das Fenster verlässt.']],
      ['Über eine Abweichung entscheiden',['Offene Abweichungen stehen mit der betroffenen Charge in der Liste. <b>Decide</b> anklicken, die Entscheidung wählen und Begründung und Nachweis angeben.']]]},
  dispatch:{what:'Scan-geprüfte Verladung, damit nur freigegebene Teile zum richtigen Kunden gelangen.',who:'Kundenrollen und Plattform-Admins.',
    tasks:[['Teile versenden',['<b>Build pallet</b>: die Kartons für die Palette wählen.','<b>New shipment</b>: Kunde, Kanal, Ziel, Kundenbestellung und Lieferscheinnummer.','<b>Scan & load</b>: jede Palette oder jeden Karton scannen. Nicht freigegebene Teile oder Teile für einen anderen Kunden werden abgewiesen.','Den <b>Delivery note</b> drucken.']]]},
  fieldReturns:{what:'Reklamationen, Garantieansprüche und Feldausfälle, verknüpft mit der Fertigung der Teile.',who:'Kundenrollen und Plattform-Admins erfassen; Werksleitung und Admins entscheiden.',
    tasks:[['Einen Rückläufer erfassen',['<b>Record field return</b> anklicken: Art, Kunde, Etikett oder Chargennummer, Fehler, Menge und Beschreibung.','<b>Check claim</b> prüft, ob der reklamierende Kunde diese Teile erhalten hat und ob Garantie besteht.']],
      ['Entscheiden',['<b>Decide</b> anklicken: Entscheidung, Grundursache und Abstellmaßnahme (8D).']]]},

  // ---------- Instandhaltung ----------
  dashboard:{what:'Offene Störungen, Wiederholfehler, Reaktionszeiten nach Priorität und anstehende Wartungstermine.',who:'Alle, beschränkt auf die eigenen Daten.',
    tasks:[['Die Übersicht nutzen',['Unter <b>Laufende Arbeiten</b> eine Störmeldung anklicken, um sie zu öffnen.','<b>Wiederholfehler (90 Tage)</b> zeigt die Maschinen, die am häufigsten ausfallen – eine anklicken für ihren Datensatz.','<b>Records to complete</b> listet Maschinen, bei denen Pflichtparameter noch fehlen.']]]},
  tickets:{what:'Störmeldungen und Servicearbeiten, von der Meldung bis zur Abnahme.',who:'Kundenrollen und interne Mitarbeiter melden; die Disposition weist zu; Techniker und Partner bearbeiten zugewiesene Störmeldungen.',
    tasks:[['Eine Störung melden',['<b>Störung melden</b> anklicken.','Die Maschine wählen (ihr QR-Etikett oder ihren Tag scannen, wenn die Scan-Regel es verlangt), Problem, Symptome und Fehlercodes beschreiben.','Maschinenzustand, Priorität und Auswirkung festlegen und angeben, ob jemand gefährdet ist. Speichern.']],
      ['Eine Störmeldung verfolgen',['Mit Filtern und Suche finden und den Titel anklicken. Siehe die Hilfe <i>Störmeldung</i> auf dieser Seite.']]]},
  ticket:{title:'Störmeldung',what:'Eine Störung: Meldung, Zuweisung, Arbeiten, Ersatzteile, Checkliste, Nachweise und Abnahme.',
    tasks:[['Zuweisen (Disposition / Admin)',['<b>Techniker zuweisen</b> anklicken und einen Techniker oder Servicepartner wählen.']],
      ['Bearbeiten',['<b>Status ändern</b>: angenommen → in Arbeit (oder eskaliert / abgelehnt mit Notiz).','<b>Ausgeführte Arbeit erfassen</b>: durchgeführte Arbeiten, Zeitaufwand, verbaute Teile.','<b>Prüfpunkt hinzufügen</b>, <b>Ersatzteil anfordern</b> und <b>Foto / Nachweis anhängen</b> nach Bedarf.']],
      ['Abschließen',['<b>Status ändern</b> auf abgeschlossen: Ausfallart, Grundursache und Maßnahme (ISO 14224) sowie Stillstand angeben. Die Maschine scannen, wenn die Scan-Regel es verlangt.','<b>Kundenabnahme</b> vor Ort: Name und Unterschrift des Unterzeichners.']]],
    tips:['Die Disposition kann ohne Scan fortfahren, wenn sie einen Grund angibt; er bleibt an der Störmeldung.']},
  equipment:{what:'Maschinen, Werkzeuge und Peripheriegeräte mit technischen Parametern, Dokumenten und Historie.',who:'Kunden-Admins und Plattform-Admins legen an; die Disposition kann bearbeiten.',
    tasks:[['Eine Anlage anlegen',['<b>Add equipment</b> anklicken: Werk, Maschinentyp, Inventarnummer, Hersteller, Modell, Seriennummer, Baujahr.','Kritikalität, Status und Standort festlegen, dann die Pflichtparameter für diesen Maschinentyp ausfüllen.']],
      ['Eine Maschine finden',['Die Liste durchsuchen oder filtern, dann die Inventarnummer anklicken.']],
      ['Eine Maschine korrigieren',['In ihrer Zeile (oder im Maschinendatensatz) <b>Bearbeiten</b> anklicken, um alle Felder zu prüfen und zu ändern: Werk, Maschinentyp, Inventarnummer, QR-Etikett, RFID-Tag, Hersteller, Modell, Seriennummer, Einstufung und technische Parameter.','Bei einem neuen Maschinentyp werden die technischen Parameter für diesen Typ abgefragt.']]],
    tips:['„Incomplete“ kennzeichnet Maschinen, bei denen Pflichtparameter fehlen.']},
  equipmentRecord:{title:'Maschinendatensatz',what:'Alles zu einer Maschine: Kennzeichnung, Parameter, Live-Daten, Dokumente, Etikett und Störmeldungen.',
    tasks:[['Häufige Aktionen',['<b>Bearbeiten</b>, um Angaben zu ändern.','<b>Störung melden</b> für diese Maschine.','<b>Attach manual or document</b> (PDF oder Bild).','<b>Connect IoT device</b>: die externe Geräte-ID aus Ihrem Maschinendatensystem eintragen und festlegen, wann die Daten als veraltet gelten.','Das <b>Equipment label</b> (QR) drucken und an der Maschine anbringen, damit an der Maschine gescannt werden kann.']]]},
  condition:{what:'Maschinenzustand aus Sensormesswerten, beurteilt gegen Warn- und kritische Grenzwerte.',who:'Kundenrollen, Disposition und Plattform-Admins; Werksleitung, Admins und Disposition bearbeiten Grenzwerte.',
    tasks:[['Einen Messwert prüfen',['Einen Parameternamen anklicken, um seinen Verlauf zu sehen.']],
      ['Grenzwerte festlegen',['Bei der Maschine <b>Edit alarm limits</b> anklicken und je Parameter Warn- und kritische Grenzwerte festlegen. Wird ein Grenzwert überschritten, entsteht ein Alarm.']]]},
  contracts:{what:'Jährliche Wartungsverträge: Abdeckung, Reaktionszeiten und geplante Termine.',who:'Plattform-Admins, Kunden-Admins und Disposition legen an und bearbeiten; alle anderen lesen.',
    tasks:[['Einen Vertrag anlegen',['<b>Add service contract</b> anklicken: Kunde, Nummer, Titel, Laufzeit und Kündigungsfrist.','Servicezeiten, Reaktions- und Wiederherstellungszeiten, Wartungstermine pro Jahr, den ersten Termin und die abgedeckten Maschinen festlegen.']],
      ['Planen und verlängern',['<b>Termin planen</b> plant einen Termin an einer Maschine.','<b>Edit contract</b> ändert Nummer, Titel, Laufzeit, abgedeckte Maschinen, Service-Level, Leistungen, Ausschlüsse oder Status – auch um einen abgelaufenen Vertrag zu verlängern.','<b>Bearbeiten</b> bei einem geplanten Termin verschiebt ihn, ändert den Umfang oder storniert ihn; <b>Abgeschlossen</b> markiert ihn als erledigt.']]],
    tips:['Maschinen ohne Vertrag verwenden die Standard-Reaktionszeiten unter <b>Einstellungen</b>.','Eine Maschine mit geplanten Terminen kann nicht aus dem Vertrag entfernt werden, und die Laufzeit kann nicht über diese Termine hinaus verschoben werden, bis sie abgeschlossen, verschoben oder storniert sind.']},
  parts:{what:'Ersatzteilanforderungen: Anforderung → Angebot → Freigabe → Bestellung → Lieferung.',who:'Angefordert aus einer Störmeldung; Partner bieten an; Kunden-Admins und Werksleitung geben frei.',
    tasks:[['Ein Teil anfordern',['In der Störmeldung <b>Ersatzteil anfordern</b> anklicken: Teilenummer, Hersteller, Beschreibung, Menge, Einheit und Dringlichkeit.']],
      ['Anbieten und freigeben',['Der Partner verwendet <b>Angebot senden</b>: Preis, Währung, Lieferzeit und Gültigkeit.','Der Kunde öffnet <b>Angebote</b> und gibt eines frei, bevor es abläuft.']]]},
  assets:{what:'Wo sich Werkzeuge, Vorrichtungen, Messmittel und Wagen befinden – über BLE-Beacons und RFID-Tags.',who:'Kundenrollen, Disposition und Plattform-Admins; Verantwortliche legen Zonen und Assets an.',
    tasks:[['Ortung einrichten',['<b>Add location zone</b>: Werk, Name, Art und die Leser- bzw. Gateway-ID.','<b>Add tracked asset</b>: Name, Art, Technik, Heimatzone, verknüpfte Anlage und ab wann es als vermisst gemeldet wird. Für die <b>Tag ID</b> den Code auf dem Beacon mit <b>Scan QR</b> lesen, auf einem Android-Telefon mit NFC <b>Read RFID/NFC tag</b> verwenden, ein Handlesegerät benutzen oder sie eintippen.']],
      ['Tag oder Lesegerät ersetzen',['Das Asset bzw. die Zone <b>Bearbeiten</b> und die neue Tag- oder Lesegeräte-ID scannen oder eintippen. Der Ortungsverlauf bleibt erhalten.']],
      ['Ein Asset finden',['Die Liste durchsuchen; <b>Location history</b> zeigt, wo es war.']]]},

  // ---------- Energie, Sicherheit ----------
  energy:{what:'Stromverbrauch, Energie pro kg, verschwendete Energie, Lastspitzen, CO₂ und Kosten.',who:'Kundenrollen, Disposition und Plattform-Admins.',
    tasks:[['Energie auswerten',['Oben Werk, Maschine und Zeitraum wählen.','Die Maschinen unter <b>By machine</b> vergleichen: kWh pro kg zeigt die Effizienz; verschwendet ist Energie, die ohne Fertigung verbraucht wurde.']]],
    tips:['Strompreis und Emissionsfaktor werden je Firma unter <b>Firmen, Werke & Benutzer › Bearbeiten</b> festgelegt.']},
  safety:{what:'Erkannte und gemeldete Sicherheitsereignisse, ihre Untersuchung und Frühindikatoren.',who:'Kundenrollen, Disposition und Plattform-Admins.',
    tasks:[['Ein Ereignis melden',['<b>Report safety event</b> anklicken: Werk, was passiert ist, Bereich, Maschine, Zeitpunkt und eine Beschreibung.']],
      ['Untersuchen und abschließen',['Bei einem offenen Ereignis <b>Start investigation</b>.','<b>Close event</b> mit Grundursache und Abstellmaßnahme.']]]},

  // ---------- Administration ----------
  organisation:{what:'Kundenfirmen, ihre Werke und die Benutzerkonten.',who:'Plattform-Admins und Kunden-Admins; Partner-Admins verwalten ihre eigenen Benutzer.',
    tasks:[['Eine Firma anlegen ('+ADMIN+')',['<b>Add company</b> anklicken: Name, Land, USt-IdNr., Kontakt, Strompreis, Emissionsfaktor, Währung, Einheiten und Sprache.']],
      ['Ein Werk anlegen',['<b>Add plant</b> anklicken: Firma, Name, Adresse, Land, Servicegebiet und Schichtmodell.','Dann beim Werk <b>Edit shifts</b>, um die geplanten Schichtzeiten festzulegen.']],
      ['Einen Benutzer anlegen',['<b>Add user</b> anklicken: Rolle, Firma (oder Servicepartner), Name, Funktion, E-Mail und ein vorläufiges Passwort.','Das Passwort weitergeben; es muss bei der ersten Anmeldung geändert werden.']],
      ['Einen Benutzer ändern',['<b>Bearbeiten</b> ändert Name, Funktion, Telefon und bei Technikern Servicegebiete und Fähigkeiten.','Rolle, Firma und E-Mail bleiben wie angelegt: das Konto <b>Deaktivieren</b> und ein neues anlegen, um sie zu ändern.']],
      ['Einem Benutzer helfen',['<b>Passwort zurücksetzen</b> vergibt ein neues vorläufiges Passwort.','<b>Vision duties</b> legt fest, welche Vision-Alarme er erhält.']]]},
  providers:{what:'Zugelassene externe Servicepartner, denen Störmeldungen zugewiesen werden können.',who:'Plattform-Admins bearbeiten; Disposition und Techniker lesen.',
    tasks:[['Einen Partner anlegen',['<b>Add service provider</b> anklicken: Name, Land, Zertifizierungen, Kontakt und Gültigkeit der Haftpflichtversicherung.','Dann seine Benutzer unter <b>Firmen, Werke & Benutzer</b> mit einer Partnerrolle anlegen.']]]},
  settings:{what:'Stammdaten und Vorgaben, die überall auf der Plattform gelten.',who:'Nur der Plattform-Admin kann sie ändern; alle anderen lesen.',
    tasks:[['Codelisten',['Mit <b>+ Add</b> neben einer Liste einen Wert hinzufügen; ✕ an einem Wert entfernt ihn.']],
      ['Servicegebiete und Checklisten',['<b>Add service area</b> / <b>Rename area</b>.','<b>Edit checklist</b> legt die Standard-Prüfpunkte je Maschinentyp fest.']],
      ['Reaktionszeiten',['Stunden je Priorität festlegen. Gilt, wenn kein Vertrag die Maschine abdeckt.']],
      ['Scan an der Maschine',['Festlegen, ob das Scannen des QR-Etiketts oder Tags der Maschine beim Melden und beim Abschließen einer Störmeldung Pflicht oder optional ist.']]]},
  integrations:{what:'Die Maschinendaten-Anbindung: Synchronisierungsläufe, Geräteanbindungen und Datensätze in Quarantäne.',who:'Plattform-Admins, Disposition und Kunden-Admins.',
    tasks:[['Eine Maschine anbinden',['Die Maschine im <b>Anlagenverzeichnis</b> öffnen und <b>Connect IoT device</b> anklicken.']],
      ['Ein Gerät ändern',['Unter <b>Device mappings</b> verschiebt <b>Bearbeiten</b> das Gerät auf eine andere Maschine derselben Firma oder ändert, wann seine Daten als veraltet gelten.','<b>Deaktivieren</b> weist seine Messwerte zurück, bis es wieder aktiviert wird.']],
      ['Die Anbindung prüfen',['<b>Jetzt synchronisieren</b> holt neue Daten sofort.','<b>Recent sync runs</b> zeigt Zähler und Fehler; <b>Quarantined records</b> zeigt Daten, die nicht gelesen werden konnten.']]]},
  audit:{what:'Jede Änderung, wer sie vorgenommen hat und wann.',who:'Plattform-Admins und Kunden-Admins.',tasks:[['Eine Änderung finden',['Nach Aktion, Datensatz oder Benutzername suchen oder nach Datensatztyp filtern.']]]},
  account:{what:'Ihr Profil, Ihre Sprache und Ihr Passwort.',who:'Alle.',
    tasks:[['Passwort ändern',['Unter <b>Change password</b> das aktuelle und das neue Passwort eingeben.']],['Sprache ändern',['Die Sprachauswahl unter Ihrem Namen im Menü verwenden.']]]},
};
