// Converts the final SQLite schema (after all legacy migrations) plus migration-inserted reference rows into one PostgreSQL baseline.
import { DatabaseSync } from 'node:sqlite';
import { writeFileSync } from 'node:fs';
const db = new DatabaseSync(process.argv[2]);
const out = [];
const fks = [];

function splitTop(s) { const parts = []; let depth = 0, q = false, cur = '';
  for (const ch of s) { if (ch === "'") q = !q; if (!q && ch === '(') depth++; if (!q && ch === ')') depth--;
    if (!q && depth === 0 && ch === ',') { parts.push(cur.trim()); cur = ''; } else cur += ch; }
  if (cur.trim()) parts.push(cur.trim()); return parts; }

const TYPES = { INTEGER: 'BIGINT', REAL: 'DOUBLE PRECISION', TEXT: 'TEXT', BLOB: 'BYTEA', NUMERIC: 'NUMERIC' };
const tables = db.prepare("SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name<>'schema_migrations' ORDER BY rowid").all();
for (const t of tables) {
  const name = t.name;
  const body = t.sql.slice(t.sql.indexOf('(') + 1, t.sql.lastIndexOf(')'));
  const defs = splitTop(body).map((d) => {
    if (/^(PRIMARY KEY|UNIQUE|CHECK)\b/i.test(d)) return d;
    const fk = /^FOREIGN KEY\s*\(([^)]+)\)\s*REFERENCES\s+"?(\w+)"?\s*\(([^)]+)\)(.*)$/is.exec(d);
    if (fk) { fks.push([name, fk[1], fk[2], fk[3], fk[4]]); return null; }
    const m = /^("?\w+"?)\s+(\w+)(.*)$/s.exec(d);
    if (!m) throw new Error(`Cannot parse ${name}: ${d}`);
    let [, col, type, rest] = m;
    const ref = /\s*REFERENCES\s+"?(\w+)"?\s*\((\w+)\)((?:\s+ON\s+(?:DELETE|UPDATE)\s+(?:CASCADE|RESTRICT|NO ACTION|SET NULL|SET DEFAULT))*)/i.exec(rest);
    if (ref) { fks.push([name, col, ref[1], ref[2], ref[3]]); rest = rest.replace(ref[0], ''); }
    return `${col} ${TYPES[type.toUpperCase()] ?? type}${rest}`;
  }).filter(Boolean);
  out.push(`CREATE TABLE "${name}" (\n  ${defs.join(',\n  ')}\n);`);
}
for (const i of db.prepare("SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL").all()) out.push(i.sql + ';');

// Reference data written by the legacy migrations
const lit = (v) => v === null ? 'NULL' : typeof v === 'number' || typeof v === 'bigint' ? String(v) : `'${String(v).replace(/'/g, "''")}'`;
for (const { name } of tables) {
  const rows = db.prepare(`SELECT * FROM "${name}"`).all();
  if (!rows.length) continue;
  const cols = Object.keys(rows[0]);
  out.push(`INSERT INTO "${name}" (${cols.join(',')}) VALUES\n${rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(',')})`).join(',\n')}\nON CONFLICT DO NOTHING;`);
}
fks.forEach(([t, c, rt, rc, act = ''], i) => out.push(`ALTER TABLE "${t}" ADD CONSTRAINT fk_${t}_${c.replace(/\W/g, '_')}_${i} FOREIGN KEY (${c}) REFERENCES "${rt}"(${rc})${act.trimEnd()};`));
writeFileSync(process.argv[3], `-- PostgreSQL baseline: the schema and reference data produced by legacy SQLite migrations 001–017
-- (kept in migrations/sqlite-legacy for history). Generated by scripts/schema2pg.mjs; new changes go in 002_*.sql onwards.\n\n${out.join('\n\n')}\n`);
console.log(`${tables.length} tables, ${fks.length} foreign keys`);
