-- Smart factory, stages 3 and 4: traceability, vision quality, safety, and tracking of tools and trolleys.

-- Traceability: material lots go into production batches made on a machine with a mould, by an operator, at set
-- process parameters. Lot → batches (forward) and batch → lots (backward) make recalls targeted.
CREATE TABLE IF NOT EXISTS material_lots (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(id), lot_number TEXT NOT NULL, material TEXT NOT NULL, supplier TEXT NOT NULL, received_at TEXT NOT NULL, quantity_kg REAL NOT NULL, status TEXT NOT NULL DEFAULT 'released' CHECK(status IN ('released','quarantined','consumed')), certificate TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, UNIQUE(company_id,lot_number));
CREATE TABLE IF NOT EXISTS batches (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(id), batch_number TEXT NOT NULL, product_id TEXT NOT NULL REFERENCES products(id), equipment_id TEXT NOT NULL REFERENCES equipment(id), mould_id TEXT REFERENCES equipment(id), operator_name TEXT NOT NULL, planned_qty REAL NOT NULL, status TEXT NOT NULL DEFAULT 'running' CHECK(status IN ('running','completed','on_hold','released','scrapped')), started_at TEXT NOT NULL, ended_at TEXT, good_qty REAL, scrap_qty REAL, process_params TEXT NOT NULL DEFAULT '{}', hold_reason TEXT, created_at TEXT NOT NULL, UNIQUE(company_id,batch_number));
CREATE INDEX IF NOT EXISTS idx_batches_machine_time ON batches(equipment_id,started_at);
CREATE TABLE IF NOT EXISTS batch_materials (batch_id TEXT NOT NULL REFERENCES batches(id), lot_id TEXT NOT NULL REFERENCES material_lots(id), quantity_kg REAL, PRIMARY KEY(batch_id,lot_id));

-- Vision quality: inspection results per machine, camera station and interval, with rejects by defect type.
CREATE TABLE IF NOT EXISTS vision_results (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(id), equipment_id TEXT NOT NULL REFERENCES equipment(id), station TEXT NOT NULL, period_start TEXT NOT NULL, period_minutes INTEGER NOT NULL, inspected INTEGER NOT NULL, rejected INTEGER NOT NULL, defects TEXT NOT NULL DEFAULT '{}', source TEXT NOT NULL, UNIQUE(equipment_id,station,period_start));

-- Asset tracking zones (each with the BLE gateway or RFID reader that covers it) and tagged assets.
CREATE TABLE IF NOT EXISTS zones (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(id), plant_id TEXT NOT NULL REFERENCES plants(id), name TEXT NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('production','storage','tool_room','maintenance','dock','restricted','outside')), reader_id TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tracked_assets (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(id), plant_id TEXT NOT NULL REFERENCES plants(id), tag_id TEXT NOT NULL UNIQUE, tag_type TEXT NOT NULL CHECK(tag_type IN ('ble','rfid','uwb')), kind TEXT NOT NULL CHECK(kind IN ('mould','tool','trolley','gauge','forklift','fixture','container','other')), name TEXT NOT NULL, equipment_id TEXT REFERENCES equipment(id), home_zone_id TEXT REFERENCES zones(id), last_zone_id TEXT REFERENCES zones(id), last_seen_at TEXT, battery_pct INTEGER, missing_after_hours INTEGER NOT NULL DEFAULT 24, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS asset_sightings (asset_id TEXT NOT NULL REFERENCES tracked_assets(id), seen_at TEXT NOT NULL, zone_id TEXT NOT NULL REFERENCES zones(id), rssi INTEGER, PRIMARY KEY(asset_id,seen_at));

-- Safety: detected events (cameras, wearables, sensors) and reported ones (people), investigated and closed with
-- a corrective action.
CREATE TABLE IF NOT EXISTS safety_events (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(id), plant_id TEXT NOT NULL REFERENCES plants(id), zone_id TEXT REFERENCES zones(id), equipment_id TEXT REFERENCES equipment(id), event_type TEXT NOT NULL, severity TEXT NOT NULL CHECK(severity IN ('info','warning','critical')), source TEXT NOT NULL CHECK(source IN ('camera','wearable','sensor','person')), description TEXT NOT NULL, occurred_at TEXT NOT NULL, reported_by TEXT REFERENCES users(id), status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','investigating','closed')), lost_time INTEGER NOT NULL DEFAULT 0, root_cause TEXT, corrective_action TEXT, closed_by TEXT REFERENCES users(id), closed_at TEXT, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_safety_company_time ON safety_events(company_id,occurred_at DESC);
