-- PostgreSQL baseline: the schema and reference data produced by legacy SQLite migrations 001–017
-- (kept in migrations/sqlite-legacy for history). Generated by backend/scripts/schema2pg.mjs; new changes go in 002_*.sql onwards.

CREATE TABLE "companies" (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  timezone TEXT NOT NULL DEFAULT 'UTC',
  currency TEXT NOT NULL DEFAULT 'USD',
  units TEXT NOT NULL DEFAULT 'metric',
  locale TEXT NOT NULL DEFAULT 'en',
  created_at TEXT NOT NULL,
  country TEXT NOT NULL DEFAULT '',
  contact_name TEXT NOT NULL DEFAULT '',
  contact_email TEXT NOT NULL DEFAULT '',
  contact_phone TEXT NOT NULL DEFAULT '',
  tax_id TEXT NOT NULL DEFAULT '',
  energy_price_per_kwh DOUBLE PRECISION,
  grid_co2_kg_per_kwh DOUBLE PRECISION,
  vision_ai_review TEXT NOT NULL DEFAULT 'off' CHECK(vision_ai_review IN ('off','manual','auto'))
);

CREATE TABLE "providers" (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  approved BIGINT NOT NULL DEFAULT 0,
  service_areas TEXT NOT NULL,
  skills TEXT NOT NULL,
  created_at TEXT NOT NULL,
  contact_name TEXT NOT NULL DEFAULT '',
  contact_email TEXT NOT NULL DEFAULT '',
  contact_phone TEXT NOT NULL DEFAULT '',
  country TEXT NOT NULL DEFAULT '',
  insurance_expiry TEXT,
  certifications TEXT NOT NULL DEFAULT ''
);

CREATE TABLE "users" (
  id TEXT PRIMARY KEY,
  company_id TEXT,
  provider_id TEXT,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('platform_admin','customer_admin','plant_manager','maintenance','dispatcher','engineer','provider_admin','provider_engineer')),
  active BIGINT NOT NULL DEFAULT 1,
  service_areas TEXT NOT NULL DEFAULT '[]',
  skills TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL,
  locale TEXT,
  session_version BIGINT NOT NULL DEFAULT 0,
  must_change_password BIGINT NOT NULL DEFAULT 0,
  phone TEXT NOT NULL DEFAULT '',
  job_title TEXT NOT NULL DEFAULT '',
  alert_emails BIGINT NOT NULL DEFAULT 1,
  vision_duties TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE "plants" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  name TEXT NOT NULL,
  address TEXT NOT NULL DEFAULT '',
  country TEXT NOT NULL,
  service_area TEXT NOT NULL,
  timezone TEXT NOT NULL,
  created_at TEXT NOT NULL,
  operating_pattern TEXT NOT NULL DEFAULT '24x7'
);

CREATE TABLE "equipment" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  plant_id TEXT NOT NULL,
  machine_type TEXT NOT NULL CHECK(machine_type IN ('injection','blow','extrusion','mould','auxiliary')),
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  serial_number TEXT NOT NULL,
  location TEXT NOT NULL,
  qr_code TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL,
  asset_tag TEXT,
  criticality TEXT NOT NULL DEFAULT 'B' CHECK(criticality IN ('A','B','C')),
  status TEXT NOT NULL DEFAULT 'in_service' CHECK(status IN ('in_service','standby','out_of_service','decommissioned')),
  year_built BIGINT,
  commissioned_at TEXT,
  warranty_until TEXT,
  specs TEXT NOT NULL DEFAULT '{}',
  rfid_tag TEXT,
  image_attachment_id TEXT,
  UNIQUE(company_id,serial_number)
);

CREATE TABLE "contracts" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  title TEXT NOT NULL,
  starts_at TEXT NOT NULL,
  renews_at TEXT NOT NULL,
  commitments TEXT NOT NULL,
  exclusions TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  response_hours BIGINT,
  contract_number TEXT,
  coverage_hours TEXT NOT NULL DEFAULT '8x5',
  restore_hours BIGINT,
  visits_per_year BIGINT NOT NULL DEFAULT 0,
  notice_days BIGINT NOT NULL DEFAULT 60
);

CREATE TABLE "contract_equipment" (
  contract_id TEXT NOT NULL,
  equipment_id TEXT NOT NULL,
  PRIMARY KEY(contract_id,equipment_id)
);

CREATE TABLE "visits" (
  id TEXT PRIMARY KEY,
  contract_id TEXT NOT NULL,
  company_id TEXT NOT NULL,
  equipment_id TEXT NOT NULL,
  due_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'scheduled',
  notes TEXT NOT NULL DEFAULT ''
);

CREATE TABLE "tickets" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  plant_id TEXT NOT NULL,
  equipment_id TEXT NOT NULL,
  title TEXT NOT NULL,
  priority TEXT NOT NULL CHECK(priority IN ('low','medium','high','critical')),
  symptoms TEXT NOT NULL,
  error_codes TEXT NOT NULL DEFAULT '',
  production_impact TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','assigned','accepted','in_progress','escalated','completed')),
  assigned_user_id TEXT,
  assigned_provider_id TEXT,
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  first_response_at TEXT,
  completed_at TEXT,
  downtime_minutes BIGINT NOT NULL DEFAULT 0,
  failure_category TEXT,
  machine_state TEXT,
  safety_issue BIGINT NOT NULL DEFAULT 0,
  occurred_at TEXT,
  failure_mode TEXT,
  root_cause TEXT,
  action_taken TEXT,
  raised_via TEXT,
  raised_scan_at TEXT,
  closed_via TEXT,
  closed_scan_at TEXT,
  scan_override_reason TEXT
);

CREATE TABLE "ticket_events" (
  id TEXT PRIMARY KEY,
  ticket_id TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  detail TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE "checklist_entries" (
  id TEXT PRIMARY KEY,
  ticket_id TEXT NOT NULL,
  item TEXT NOT NULL,
  done BIGINT NOT NULL DEFAULT 0,
  note TEXT NOT NULL DEFAULT '',
  updated_by TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE "work_logs" (
  id TEXT PRIMARY KEY,
  ticket_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  description TEXT NOT NULL,
  minutes BIGINT NOT NULL,
  parts_used TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL
);

CREATE TABLE "parts_requests" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  ticket_id TEXT NOT NULL,
  item TEXT NOT NULL,
  quantity BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'requested',
  created_at TEXT NOT NULL,
  fulfilment_reference TEXT NOT NULL DEFAULT '',
  updated_at TEXT,
  part_number TEXT NOT NULL DEFAULT '',
  unit TEXT NOT NULL DEFAULT 'pcs',
  urgency TEXT NOT NULL DEFAULT 'normal',
  manufacturer TEXT NOT NULL DEFAULT ''
);

CREATE TABLE "quotations" (
  id TEXT PRIMARY KEY,
  request_id TEXT NOT NULL,
  company_id TEXT NOT NULL,
  amount_minor BIGINT NOT NULL,
  currency TEXT NOT NULL,
  lead_days BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  approved_by TEXT,
  created_at TEXT NOT NULL,
  valid_until TEXT
);

CREATE TABLE "attachments" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  entity_type TEXT NOT NULL CHECK(entity_type IN ('equipment','ticket','work_log')),
  entity_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  filename TEXT NOT NULL,
  mime TEXT NOT NULL,
  size_bytes BIGINT NOT NULL,
  storage_name TEXT NOT NULL,
  uploaded_by TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE "audit_events" (
  id TEXT PRIMARY KEY,
  actor_id TEXT NOT NULL,
  company_id TEXT,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  detail TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE "device_mappings" (
  id TEXT PRIMARY KEY,
  external_device_id TEXT NOT NULL UNIQUE,
  company_id TEXT NOT NULL,
  equipment_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  active BIGINT NOT NULL DEFAULT 1,
  stale_after_minutes BIGINT NOT NULL DEFAULT 30
);

CREATE TABLE "readings" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  equipment_id TEXT NOT NULL,
  external_device_id TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  received_at TEXT NOT NULL,
  running_hours DOUBLE PRECISION,
  cycle_count BIGINT,
  temperature_c DOUBLE PRECISION,
  alarm_code TEXT,
  raw_json TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'push',
  quality_flags TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE "offline_actions" (
  user_id TEXT NOT NULL,
  client_action_id TEXT NOT NULL,
  result_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY(user_id,client_action_id)
);

CREATE TABLE "iot_alarms" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  equipment_id TEXT NOT NULL,
  external_device_id TEXT NOT NULL,
  code TEXT NOT NULL,
  severity TEXT NOT NULL CHECK(severity IN ('info','warning','critical')),
  message TEXT NOT NULL DEFAULT '',
  raised_at TEXT NOT NULL,
  cleared_at TEXT,
  received_at TEXT NOT NULL,
  source TEXT NOT NULL,
  UNIQUE(external_device_id, code, raised_at)
);

CREATE TABLE "iot_rejections" (
  id TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  external_device_id TEXT,
  reasons TEXT NOT NULL,
  raw_json TEXT NOT NULL,
  received_at TEXT NOT NULL
);

CREATE TABLE "integration_cursors" (
  adapter TEXT PRIMARY KEY,
  cursor TEXT,
  updated_at TEXT NOT NULL
);

CREATE TABLE "integration_runs" (
  id TEXT PRIMARY KEY,
  adapter TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  status TEXT NOT NULL CHECK(status IN ('running','succeeded','failed')),
  accepted BIGINT NOT NULL DEFAULT 0,
  duplicates BIGINT NOT NULL DEFAULT 0,
  rejected BIGINT NOT NULL DEFAULT 0,
  cursor_before TEXT,
  cursor_after TEXT,
  error TEXT
);

CREATE TABLE "signoffs" (
  ticket_id TEXT PRIMARY KEY,
  customer_user_id TEXT,
  signer_name TEXT NOT NULL,
  signed_at TEXT NOT NULL,
  method TEXT NOT NULL DEFAULT 'portal' CHECK(method IN ('portal','on_site')),
  signature_attachment_id TEXT,
  collected_by TEXT
);

CREATE TABLE "checklist_templates" (
  id TEXT PRIMARY KEY,
  machine_type TEXT NOT NULL CHECK(machine_type IN ('injection','blow','extrusion','mould','auxiliary')),
  position BIGINT NOT NULL,
  item TEXT NOT NULL,
  UNIQUE(machine_type,item)
);

CREATE TABLE "service_areas" (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE "settings" (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE "shifts" (
  id TEXT PRIMARY KEY,
  plant_id TEXT NOT NULL,
  name TEXT NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  days TEXT NOT NULL DEFAULT '[1,2,3,4,5,6,7]',
  created_at TEXT NOT NULL
);

CREATE TABLE "products" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  part_number TEXT NOT NULL,
  name TEXT NOT NULL,
  material TEXT NOT NULL,
  part_weight_g DOUBLE PRECISION,
  unit TEXT NOT NULL DEFAULT 'parts' CHECK(unit IN ('parts','kg','m')),
  ideal_cycle_s DOUBLE PRECISION,
  cavities BIGINT NOT NULL DEFAULT 1,
  ideal_rate_per_hour DOUBLE PRECISION NOT NULL,
  mould_id TEXT,
  default_machine_id TEXT,
  active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  customer TEXT NOT NULL DEFAULT '',
  warranty_months BIGINT NOT NULL DEFAULT 24,
  pack_qty BIGINT,
  process_window TEXT NOT NULL DEFAULT '{}',
  check_sheets TEXT NOT NULL DEFAULT '{}',
  hold_on_deviation BIGINT NOT NULL DEFAULT 0,
  UNIQUE(company_id,part_number)
);

CREATE TABLE "machine_states" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  equipment_id TEXT NOT NULL,
  state TEXT NOT NULL CHECK(state IN ('running','idle','down','setup','planned_stop','offline')),
  reason_code TEXT,
  started_at TEXT NOT NULL,
  ended_at TEXT,
  source TEXT NOT NULL
);

CREATE TABLE "production_counts" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  equipment_id TEXT NOT NULL,
  product_id TEXT,
  period_start TEXT NOT NULL,
  period_minutes BIGINT NOT NULL,
  total_qty DOUBLE PRECISION NOT NULL,
  scrap_qty DOUBLE PRECISION NOT NULL,
  unit TEXT NOT NULL,
  ideal_rate_per_hour DOUBLE PRECISION NOT NULL,
  source TEXT NOT NULL,
  UNIQUE(equipment_id,period_start)
);

CREATE TABLE "factory_cursors" (
  equipment_id TEXT NOT NULL,
  stream TEXT NOT NULL,
  until TEXT NOT NULL,
  PRIMARY KEY(equipment_id,stream)
);

CREATE TABLE "alerts" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  plant_id TEXT,
  module TEXT NOT NULL,
  severity TEXT NOT NULL CHECK(severity IN ('info','warning','critical')),
  equipment_id TEXT,
  title TEXT NOT NULL,
  detail TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','acknowledged','resolved')),
  dedupe_key TEXT NOT NULL,
  ticket_id TEXT,
  created_at TEXT NOT NULL,
  acknowledged_by TEXT,
  acknowledged_at TEXT,
  resolved_at TEXT
);

CREATE TABLE "notification_outbox" (
  id TEXT PRIMARY KEY,
  alert_id TEXT,
  channel TEXT NOT NULL,
  recipient TEXT NOT NULL,
  subject TEXT NOT NULL,
  body TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('queued','sent','failed','not_configured')),
  error TEXT,
  created_at TEXT NOT NULL,
  sent_at TEXT
);

CREATE TABLE "sensor_limits" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  equipment_id TEXT NOT NULL,
  parameter TEXT NOT NULL,
  warn_low DOUBLE PRECISION,
  warn_high DOUBLE PRECISION,
  crit_low DOUBLE PRECISION,
  crit_high DOUBLE PRECISION,
  auto_ticket BIGINT NOT NULL DEFAULT 1,
  updated_at TEXT NOT NULL,
  UNIQUE(equipment_id,parameter)
);

CREATE TABLE "condition_readings" (
  equipment_id TEXT NOT NULL,
  parameter TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  company_id TEXT NOT NULL,
  source TEXT NOT NULL,
  PRIMARY KEY(equipment_id,parameter,observed_at)
);

CREATE TABLE "energy_readings" (
  equipment_id TEXT NOT NULL,
  period_start TEXT NOT NULL,
  period_minutes BIGINT NOT NULL,
  kwh DOUBLE PRECISION NOT NULL,
  peak_kw DOUBLE PRECISION,
  company_id TEXT NOT NULL,
  source TEXT NOT NULL,
  PRIMARY KEY(equipment_id,period_start)
);

CREATE TABLE "material_lots" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  lot_number TEXT NOT NULL,
  material TEXT NOT NULL,
  supplier TEXT NOT NULL,
  received_at TEXT NOT NULL,
  quantity_kg DOUBLE PRECISION NOT NULL,
  status TEXT NOT NULL DEFAULT 'released' CHECK(status IN ('released','quarantined','consumed')),
  certificate TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  UNIQUE(company_id,lot_number)
);

CREATE TABLE "batches" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  batch_number TEXT NOT NULL,
  product_id TEXT NOT NULL,
  equipment_id TEXT NOT NULL,
  mould_id TEXT,
  operator_name TEXT NOT NULL,
  planned_qty DOUBLE PRECISION NOT NULL,
  status TEXT NOT NULL DEFAULT 'running' CHECK(status IN ('running','completed','on_hold','released','scrapped')),
  started_at TEXT NOT NULL,
  ended_at TEXT,
  good_qty DOUBLE PRECISION,
  scrap_qty DOUBLE PRECISION,
  process_params TEXT NOT NULL DEFAULT '{}',
  hold_reason TEXT,
  created_at TEXT NOT NULL,
  started_by TEXT,
  fifo_override TEXT,
  released_by TEXT,
  released_at TEXT,
  UNIQUE(company_id,batch_number)
);

CREATE TABLE "batch_materials" (
  batch_id TEXT NOT NULL,
  lot_id TEXT NOT NULL,
  quantity_kg DOUBLE PRECISION,
  PRIMARY KEY(batch_id,lot_id)
);

CREATE TABLE "vision_results" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  equipment_id TEXT NOT NULL,
  station TEXT NOT NULL,
  period_start TEXT NOT NULL,
  period_minutes BIGINT NOT NULL,
  inspected BIGINT NOT NULL,
  rejected BIGINT NOT NULL,
  defects TEXT NOT NULL DEFAULT '{}',
  source TEXT NOT NULL,
  UNIQUE(equipment_id,station,period_start)
);

CREATE TABLE "zones" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  plant_id TEXT NOT NULL,
  name TEXT NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('production','storage','tool_room','maintenance','dock','restricted','outside')),
  reader_id TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL
);

CREATE TABLE "tracked_assets" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  plant_id TEXT NOT NULL,
  tag_id TEXT NOT NULL UNIQUE,
  tag_type TEXT NOT NULL CHECK(tag_type IN ('ble','rfid','uwb')),
  kind TEXT NOT NULL CHECK(kind IN ('mould','tool','trolley','gauge','forklift','fixture','container','other')),
  name TEXT NOT NULL,
  equipment_id TEXT,
  home_zone_id TEXT,
  last_zone_id TEXT,
  last_seen_at TEXT,
  battery_pct BIGINT,
  missing_after_hours BIGINT NOT NULL DEFAULT 24,
  created_at TEXT NOT NULL
);

CREATE TABLE "asset_sightings" (
  asset_id TEXT NOT NULL,
  seen_at TEXT NOT NULL,
  zone_id TEXT NOT NULL,
  rssi BIGINT,
  PRIMARY KEY(asset_id,seen_at)
);

CREATE TABLE "safety_events" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  plant_id TEXT NOT NULL,
  zone_id TEXT,
  equipment_id TEXT,
  event_type TEXT NOT NULL,
  severity TEXT NOT NULL CHECK(severity IN ('info','warning','critical')),
  source TEXT NOT NULL CHECK(source IN ('camera','wearable','sensor','person')),
  description TEXT NOT NULL,
  occurred_at TEXT NOT NULL,
  reported_by TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','investigating','closed')),
  lost_time BIGINT NOT NULL DEFAULT 0,
  root_cause TEXT,
  corrective_action TEXT,
  closed_by TEXT,
  closed_at TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE "code_lists" (
  list TEXT NOT NULL,
  code TEXT NOT NULL,
  position BIGINT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (list,code)
);

CREATE TABLE "ticket_assistant_messages" (
  id TEXT PRIMARY KEY,
  ticket_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('user','assistant')),
  content TEXT NOT NULL,
  created_at TEXT NOT NULL,
  attachment_id TEXT
);

CREATE TABLE "ticket_guides" (
  ticket_id TEXT PRIMARY KEY,
  guide TEXT NOT NULL,
  source TEXT NOT NULL CHECK(source IN ('ai','standard')),
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE "vision_licences" (
  company_id TEXT NOT NULL,
  module TEXT NOT NULL CHECK(module IN ('ppe','fire_smoke','quality','intrusion')),
  cameras BIGINT NOT NULL CHECK(cameras>=0),
  valid_until TEXT,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (company_id,module)
);

CREATE TABLE "vision_nodes" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  plant_id TEXT NOT NULL,
  name TEXT NOT NULL,
  hardware TEXT NOT NULL DEFAULT '',
  max_streams BIGINT NOT NULL DEFAULT 16,
  key_hash TEXT NOT NULL UNIQUE,
  key_hint TEXT NOT NULL,
  active BIGINT NOT NULL DEFAULT 1,
  last_seen_at TEXT,
  agent_version TEXT,
  metrics TEXT NOT NULL DEFAULT '{}',
  config_version BIGINT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);

CREATE TABLE "vision_cameras" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  plant_id TEXT NOT NULL,
  node_id TEXT,
  name TEXT NOT NULL,
  source_type TEXT NOT NULL CHECK(source_type IN ('rtsp','http-snapshot','cognex-native','folder','csi','visionforge')),
  source_url TEXT NOT NULL DEFAULT '',
  location TEXT NOT NULL DEFAULT '',
  zone_id TEXT,
  equipment_id TEXT,
  fps BIGINT NOT NULL DEFAULT 25,
  snapshot_media_id TEXT,
  status TEXT NOT NULL DEFAULT 'unknown',
  last_seen_at TEXT,
  metrics TEXT NOT NULL DEFAULT '{}',
  active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  vendor TEXT NOT NULL DEFAULT ''
);

CREATE TABLE "vision_assignments" (
  camera_id TEXT NOT NULL,
  module TEXT NOT NULL CHECK(module IN ('ppe','fire_smoke','quality','intrusion')),
  enabled BIGINT NOT NULL DEFAULT 1,
  config TEXT NOT NULL DEFAULT '{}',
  updated_by TEXT,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (camera_id,module)
);

CREATE TABLE "vision_zones" (
  id TEXT PRIMARY KEY,
  camera_id TEXT NOT NULL,
  name TEXT NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('exclusion','tripwire','allowed_motion','ppe_zone','inspection_roi')),
  points TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'critical' CHECK(severity IN ('warning','critical')),
  classes TEXT NOT NULL DEFAULT '["person","vehicle"]',
  active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  surface_class TEXT CHECK(surface_class IN ('A','B','C'))
);

CREATE TABLE "vision_media" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('snapshot','clip','frame')),
  mime TEXT NOT NULL,
  size_bytes BIGINT NOT NULL,
  storage_name TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE "vision_events" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  plant_id TEXT NOT NULL,
  camera_id TEXT NOT NULL,
  node_id TEXT,
  module TEXT NOT NULL,
  type TEXT NOT NULL,
  severity TEXT NOT NULL CHECK(severity IN ('info','warning','critical')),
  confidence DOUBLE PRECISION,
  occurred_at TEXT NOT NULL,
  received_at TEXT NOT NULL,
  latency_ms BIGINT,
  zone_id TEXT,
  detail TEXT NOT NULL DEFAULT '{}',
  boxes TEXT NOT NULL DEFAULT '[]',
  edge_actions TEXT NOT NULL DEFAULT '{}',
  snapshot_media_id TEXT,
  clip_media_id TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','acknowledged','resolved','false_alarm')),
  acknowledged_by TEXT,
  acknowledged_at TEXT,
  resolved_by TEXT,
  resolved_at TEXT,
  resolution_note TEXT NOT NULL DEFAULT '',
  locked BIGINT NOT NULL DEFAULT 0,
  retrain BIGINT NOT NULL DEFAULT 0,
  external_id TEXT,
  alert_id TEXT,
  safety_event_id TEXT,
  UNIQUE(node_id,external_id)
);

CREATE TABLE "vision_stats" (
  camera_id TEXT NOT NULL,
  minute TEXT NOT NULL,
  module TEXT NOT NULL,
  frames BIGINT NOT NULL DEFAULT 0,
  people BIGINT NOT NULL DEFAULT 0,
  compliant BIGINT NOT NULL DEFAULT 0,
  inspected BIGINT NOT NULL DEFAULT 0,
  passed BIGINT NOT NULL DEFAULT 0,
  ignored BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (camera_id,minute,module)
);

CREATE TABLE "trace_units" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  batch_id TEXT NOT NULL,
  serial TEXT NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('part','box','pallet')),
  parent_id TEXT,
  quantity DOUBLE PRECISION NOT NULL,
  status TEXT NOT NULL DEFAULT 'packed' CHECK(status IN ('packed','shipped','returned','scrapped')),
  shipment_id TEXT,
  created_by TEXT,
  created_at TEXT NOT NULL,
  UNIQUE(company_id,serial)
);

CREATE TABLE "batch_checks" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  batch_id TEXT NOT NULL,
  gate TEXT NOT NULL CHECK(gate IN ('first_article','in_process','final_qc','packaging')),
  result TEXT NOT NULL CHECK(result IN ('pass','fail')),
  answers TEXT NOT NULL DEFAULT '[]',
  note TEXT NOT NULL DEFAULT '',
  checked_by TEXT NOT NULL,
  checked_at TEXT NOT NULL
);

CREATE TABLE "process_readings" (
  batch_id TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  parameter TEXT NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  source TEXT NOT NULL DEFAULT 'machine',
  PRIMARY KEY(batch_id,parameter,observed_at)
);

CREATE TABLE "process_deviations" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  batch_id TEXT NOT NULL,
  parameter TEXT NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  min DOUBLE PRECISION,
  max DOUBLE PRECISION,
  started_at TEXT NOT NULL,
  ended_at TEXT,
  readings BIGINT NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','accepted','rejected')),
  disposition TEXT,
  decided_by TEXT,
  decided_at TEXT
);

CREATE TABLE "shipments" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  shipment_number TEXT NOT NULL,
  customer TEXT NOT NULL,
  channel TEXT NOT NULL CHECK(channel IN ('oem','tier1','distributor','aftermarket','internal')),
  destination TEXT NOT NULL DEFAULT '',
  customer_po TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'loading' CHECK(status IN ('loading','shipped','cancelled')),
  shipped_at TEXT,
  created_by TEXT,
  created_at TEXT NOT NULL,
  UNIQUE(company_id,shipment_number)
);

CREATE TABLE "field_returns" (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  reference TEXT NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('complaint','warranty_claim','field_failure')),
  customer TEXT NOT NULL,
  serial TEXT NOT NULL DEFAULT '',
  unit_id TEXT,
  batch_id TEXT,
  quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
  defect TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  reported_at TEXT NOT NULL,
  authenticity TEXT NOT NULL CHECK(authenticity IN ('genuine','suspicious','not_found')),
  checks TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','accepted','rejected','closed')),
  root_cause TEXT,
  corrective_action TEXT,
  created_by TEXT,
  created_at TEXT NOT NULL,
  UNIQUE(company_id,reference)
);

CREATE TABLE "vision_reviews" (
  event_id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  verdict TEXT NOT NULL CHECK(verdict IN ('confirmed','doubtful','unclear')),
  reason TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  model TEXT NOT NULL,
  source TEXT NOT NULL CHECK(source IN ('manual','auto')),
  requested_by TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX idx_tickets_company_status ON tickets(company_id,status);

CREATE INDEX idx_tickets_provider ON tickets(assigned_provider_id);

CREATE INDEX idx_readings_asset_time ON readings(equipment_id,observed_at DESC);

CREATE INDEX idx_audit_company_time ON audit_events(company_id,created_at DESC);

CREATE UNIQUE INDEX idx_readings_device_time ON readings(external_device_id, observed_at);

CREATE INDEX idx_device_mappings_equipment ON device_mappings(equipment_id);

CREATE INDEX idx_alarms_asset_open ON iot_alarms(equipment_id, cleared_at);

CREATE INDEX idx_rejections_time ON iot_rejections(received_at DESC);

CREATE INDEX idx_runs_time ON integration_runs(started_at DESC);

CREATE INDEX idx_checklist_ticket ON checklist_entries(ticket_id);

CREATE INDEX idx_parts_ticket ON parts_requests(ticket_id);

CREATE INDEX idx_tickets_equipment ON tickets(equipment_id,created_at);

CREATE UNIQUE INDEX idx_equipment_asset_tag ON equipment(company_id,asset_tag) WHERE asset_tag IS NOT NULL;

CREATE UNIQUE INDEX idx_contract_number ON contracts(company_id,contract_number) WHERE contract_number IS NOT NULL;

CREATE INDEX idx_shifts_plant ON shifts(plant_id);

CREATE INDEX idx_states_asset_time ON machine_states(equipment_id,started_at);

CREATE INDEX idx_counts_asset_time ON production_counts(equipment_id,period_start);

CREATE UNIQUE INDEX idx_alerts_open_key ON alerts(dedupe_key) WHERE status<>'resolved';

CREATE INDEX idx_alerts_company_time ON alerts(company_id,created_at DESC);

CREATE INDEX idx_batches_machine_time ON batches(equipment_id,started_at);

CREATE INDEX idx_safety_company_time ON safety_events(company_id,occurred_at DESC);

CREATE UNIQUE INDEX idx_equipment_rfid ON equipment(rfid_tag) WHERE rfid_tag IS NOT NULL;

CREATE INDEX idx_assistant_ticket ON ticket_assistant_messages(ticket_id,created_at);

CREATE INDEX idx_vision_events_company ON vision_events(company_id,occurred_at);

CREATE INDEX idx_vision_events_camera ON vision_events(camera_id,occurred_at);

CREATE INDEX idx_vision_events_open ON vision_events(status,severity);

CREATE INDEX idx_trace_units_batch ON trace_units(batch_id);

CREATE INDEX idx_batch_checks_batch ON batch_checks(batch_id,gate);

CREATE INDEX idx_deviations_batch ON process_deviations(batch_id);

CREATE INDEX idx_field_returns_batch ON field_returns(batch_id);

CREATE INDEX idx_vision_reviews_company ON vision_reviews(company_id,created_at);

INSERT INTO "users" (id,company_id,provider_id,name,email,password_hash,role,active,service_areas,skills,created_at,locale,session_version,must_change_password,phone,job_title,alert_emails,vision_duties) VALUES
  ('u-system',NULL,NULL,'Automatic monitoring','system@platform.local','disabled:00','platform_admin',0,'[]','[]','2026-10-09 01:27:59',NULL,0,0,'','',1,'[]')
ON CONFLICT DO NOTHING;

INSERT INTO "checklist_templates" (id,machine_type,position,item) VALUES
  ('ct-inj-1','injection',1,'Lock-out / tag-out applied'),
  ('ct-inj-2','injection',2,'Hydraulic oil level, temperature and leaks checked'),
  ('ct-inj-3','injection',3,'Clamp unit, tie bars and platen lubrication inspected'),
  ('ct-inj-4','injection',4,'Barrel heater bands and thermocouples checked'),
  ('ct-inj-5','injection',5,'Injection pressure and cushion verified against setpoint'),
  ('ct-inj-6','injection',6,'Safety gates and emergency stops tested'),
  ('ct-inj-7','injection',7,'Machine returned to production and first parts verified'),
  ('ct-blw-1','blow',1,'Lock-out / tag-out applied'),
  ('ct-blw-2','blow',2,'Parison head and die tooling inspected'),
  ('ct-blw-3','blow',3,'Blow pin, air pressure and valves checked'),
  ('ct-blw-4','blow',4,'Mould cooling circuits checked for leaks'),
  ('ct-blw-5','blow',5,'Guards and light curtains tested'),
  ('ct-blw-6','blow',6,'Machine returned to production and first parts verified'),
  ('ct-ext-1','extrusion',1,'Lock-out / tag-out applied'),
  ('ct-ext-2','extrusion',2,'Barrel zone temperatures checked against setpoint'),
  ('ct-ext-3','extrusion',3,'Screw drive, gearbox oil and motor current checked'),
  ('ct-ext-4','extrusion',4,'Die, breaker plate and screen changer inspected'),
  ('ct-ext-5','extrusion',5,'Downstream haul-off and cooling verified'),
  ('ct-ext-6','extrusion',6,'Emergency stops tested'),
  ('ct-ext-7','extrusion',7,'Line returned to production and output verified'),
  ('ct-mld-1','mould',1,'Parting line and vents cleaned and inspected'),
  ('ct-mld-2','mould',2,'Ejector pins and return springs checked'),
  ('ct-mld-3','mould',3,'Cooling channel flow checked and no leaks'),
  ('ct-mld-4','mould',4,'Hot runner heaters and thermocouples checked'),
  ('ct-mld-5','mould',5,'Shot count recorded'),
  ('ct-mld-6','mould',6,'Mould returned to press or stored protected'),
  ('ct-aux-1','auxiliary',1,'Lock-out / tag-out applied'),
  ('ct-aux-2','auxiliary',2,'Filters inspected and cleaned'),
  ('ct-aux-3','auxiliary',3,'Temperature, dew point or flow verified against setpoint'),
  ('ct-aux-4','auxiliary',4,'Alarms and safety interlocks tested'),
  ('ct-aux-5','auxiliary',5,'Equipment returned to service')
ON CONFLICT DO NOTHING;

INSERT INTO "settings" (key,value,updated_at) VALUES
  ('default_response_hours','{"critical":4,"high":8,"medium":24,"low":72}','2026-10-09 01:27:59'),
  ('scan_policy','{"raise":"optional","close":"required"}','2026-10-09 01:27:59'),
  ('vision_settings','{"mediaRetentionDays":30,"qualityAlertRatePct":2,"clipSeconds":10,"preEventSeconds":5,"diskPrunePct":90,"broadcastGroup":"239.10.10.10","broadcastPort":5005}','2026-10-09 01:27:59')
ON CONFLICT DO NOTHING;

INSERT INTO "code_lists" (list,code,position,created_at) VALUES
  ('failure_categories','mechanical',1,'2026-10-09 01:27:59'),
  ('failure_categories','hydraulic',2,'2026-10-09 01:27:59'),
  ('failure_categories','pneumatic',3,'2026-10-09 01:27:59'),
  ('failure_categories','electrical',4,'2026-10-09 01:27:59'),
  ('failure_categories','controls',5,'2026-10-09 01:27:59'),
  ('failure_categories','heating',6,'2026-10-09 01:27:59'),
  ('failure_categories','cooling',7,'2026-10-09 01:27:59'),
  ('failure_categories','tooling',8,'2026-10-09 01:27:59'),
  ('failure_categories','material',9,'2026-10-09 01:27:59'),
  ('failure_categories','safety',10,'2026-10-09 01:27:59'),
  ('failure_categories','other',11,'2026-10-09 01:27:59'),
  ('failure_modes','fail_to_start',1,'2026-10-09 01:27:59'),
  ('failure_modes','fail_to_stop',2,'2026-10-09 01:27:59'),
  ('failure_modes','breakdown',3,'2026-10-09 01:27:59'),
  ('failure_modes','low_output',4,'2026-10-09 01:27:59'),
  ('failure_modes','erratic_operation',5,'2026-10-09 01:27:59'),
  ('failure_modes','abnormal_noise_vibration',6,'2026-10-09 01:27:59'),
  ('failure_modes','overheating',7,'2026-10-09 01:27:59'),
  ('failure_modes','external_leakage',8,'2026-10-09 01:27:59'),
  ('failure_modes','quality_defect',9,'2026-10-09 01:27:59'),
  ('failure_modes','structural_damage',10,'2026-10-09 01:27:59'),
  ('failure_modes','minor_issue',11,'2026-10-09 01:27:59'),
  ('failure_modes','other',12,'2026-10-09 01:27:59'),
  ('root_causes','design',1,'2026-10-09 01:27:59'),
  ('root_causes','installation',2,'2026-10-09 01:27:59'),
  ('root_causes','operation_error',3,'2026-10-09 01:27:59'),
  ('root_causes','maintenance_error',4,'2026-10-09 01:27:59'),
  ('root_causes','wear_and_ageing',5,'2026-10-09 01:27:59'),
  ('root_causes','contamination',6,'2026-10-09 01:27:59'),
  ('root_causes','material_or_supply',7,'2026-10-09 01:27:59'),
  ('root_causes','external_influence',8,'2026-10-09 01:27:59'),
  ('root_causes','unknown',9,'2026-10-09 01:27:59'),
  ('actions','replace',1,'2026-10-09 01:27:59'),
  ('actions','repair',2,'2026-10-09 01:27:59'),
  ('actions','adjust',3,'2026-10-09 01:27:59'),
  ('actions','modify',4,'2026-10-09 01:27:59'),
  ('actions','clean',5,'2026-10-09 01:27:59'),
  ('actions','inspect',6,'2026-10-09 01:27:59'),
  ('actions','service',7,'2026-10-09 01:27:59'),
  ('actions','overhaul',8,'2026-10-09 01:27:59'),
  ('actions','software_update',9,'2026-10-09 01:27:59'),
  ('actions','temporary_fix',10,'2026-10-09 01:27:59')
ON CONFLICT DO NOTHING;

ALTER TABLE "users" ADD CONSTRAINT fk_users_company_id_0 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD CONSTRAINT fk_users_provider_id_1 FOREIGN KEY (provider_id) REFERENCES "providers"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plants" ADD CONSTRAINT fk_plants_company_id_2 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipment" ADD CONSTRAINT fk_equipment_company_id_3 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipment" ADD CONSTRAINT fk_equipment_plant_id_4 FOREIGN KEY (plant_id) REFERENCES "plants"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipment" ADD CONSTRAINT fk_equipment_image_attachment_id_5 FOREIGN KEY (image_attachment_id) REFERENCES "attachments"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contracts" ADD CONSTRAINT fk_contracts_company_id_6 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contract_equipment" ADD CONSTRAINT fk_contract_equipment_contract_id_7 FOREIGN KEY (contract_id) REFERENCES "contracts"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contract_equipment" ADD CONSTRAINT fk_contract_equipment_equipment_id_8 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "visits" ADD CONSTRAINT fk_visits_contract_id_9 FOREIGN KEY (contract_id) REFERENCES "contracts"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "visits" ADD CONSTRAINT fk_visits_company_id_10 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "visits" ADD CONSTRAINT fk_visits_equipment_id_11 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD CONSTRAINT fk_tickets_company_id_12 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD CONSTRAINT fk_tickets_plant_id_13 FOREIGN KEY (plant_id) REFERENCES "plants"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD CONSTRAINT fk_tickets_equipment_id_14 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD CONSTRAINT fk_tickets_assigned_user_id_15 FOREIGN KEY (assigned_user_id) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD CONSTRAINT fk_tickets_assigned_provider_id_16 FOREIGN KEY (assigned_provider_id) REFERENCES "providers"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD CONSTRAINT fk_tickets_created_by_17 FOREIGN KEY (created_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_events" ADD CONSTRAINT fk_ticket_events_ticket_id_18 FOREIGN KEY (ticket_id) REFERENCES "tickets"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_events" ADD CONSTRAINT fk_ticket_events_actor_id_19 FOREIGN KEY (actor_id) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "checklist_entries" ADD CONSTRAINT fk_checklist_entries_ticket_id_20 FOREIGN KEY (ticket_id) REFERENCES "tickets"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "checklist_entries" ADD CONSTRAINT fk_checklist_entries_updated_by_21 FOREIGN KEY (updated_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "work_logs" ADD CONSTRAINT fk_work_logs_ticket_id_22 FOREIGN KEY (ticket_id) REFERENCES "tickets"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "work_logs" ADD CONSTRAINT fk_work_logs_user_id_23 FOREIGN KEY (user_id) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "parts_requests" ADD CONSTRAINT fk_parts_requests_company_id_24 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "parts_requests" ADD CONSTRAINT fk_parts_requests_ticket_id_25 FOREIGN KEY (ticket_id) REFERENCES "tickets"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "quotations" ADD CONSTRAINT fk_quotations_request_id_26 FOREIGN KEY (request_id) REFERENCES "parts_requests"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "quotations" ADD CONSTRAINT fk_quotations_company_id_27 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "quotations" ADD CONSTRAINT fk_quotations_approved_by_28 FOREIGN KEY (approved_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attachments" ADD CONSTRAINT fk_attachments_company_id_29 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attachments" ADD CONSTRAINT fk_attachments_uploaded_by_30 FOREIGN KEY (uploaded_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_events" ADD CONSTRAINT fk_audit_events_actor_id_31 FOREIGN KEY (actor_id) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "device_mappings" ADD CONSTRAINT fk_device_mappings_company_id_32 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "device_mappings" ADD CONSTRAINT fk_device_mappings_equipment_id_33 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "readings" ADD CONSTRAINT fk_readings_company_id_34 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "readings" ADD CONSTRAINT fk_readings_equipment_id_35 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "offline_actions" ADD CONSTRAINT fk_offline_actions_user_id_36 FOREIGN KEY (user_id) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "iot_alarms" ADD CONSTRAINT fk_iot_alarms_company_id_37 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "iot_alarms" ADD CONSTRAINT fk_iot_alarms_equipment_id_38 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "signoffs" ADD CONSTRAINT fk_signoffs_ticket_id_39 FOREIGN KEY (ticket_id) REFERENCES "tickets"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "signoffs" ADD CONSTRAINT fk_signoffs_customer_user_id_40 FOREIGN KEY (customer_user_id) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "signoffs" ADD CONSTRAINT fk_signoffs_signature_attachment_id_41 FOREIGN KEY (signature_attachment_id) REFERENCES "attachments"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "signoffs" ADD CONSTRAINT fk_signoffs_collected_by_42 FOREIGN KEY (collected_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shifts" ADD CONSTRAINT fk_shifts_plant_id_43 FOREIGN KEY (plant_id) REFERENCES "plants"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD CONSTRAINT fk_products_company_id_44 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD CONSTRAINT fk_products_mould_id_45 FOREIGN KEY (mould_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD CONSTRAINT fk_products_default_machine_id_46 FOREIGN KEY (default_machine_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "machine_states" ADD CONSTRAINT fk_machine_states_company_id_47 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "machine_states" ADD CONSTRAINT fk_machine_states_equipment_id_48 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "production_counts" ADD CONSTRAINT fk_production_counts_company_id_49 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "production_counts" ADD CONSTRAINT fk_production_counts_equipment_id_50 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "production_counts" ADD CONSTRAINT fk_production_counts_product_id_51 FOREIGN KEY (product_id) REFERENCES "products"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "factory_cursors" ADD CONSTRAINT fk_factory_cursors_equipment_id_52 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alerts" ADD CONSTRAINT fk_alerts_company_id_53 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alerts" ADD CONSTRAINT fk_alerts_plant_id_54 FOREIGN KEY (plant_id) REFERENCES "plants"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alerts" ADD CONSTRAINT fk_alerts_equipment_id_55 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alerts" ADD CONSTRAINT fk_alerts_ticket_id_56 FOREIGN KEY (ticket_id) REFERENCES "tickets"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alerts" ADD CONSTRAINT fk_alerts_acknowledged_by_57 FOREIGN KEY (acknowledged_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_outbox" ADD CONSTRAINT fk_notification_outbox_alert_id_58 FOREIGN KEY (alert_id) REFERENCES "alerts"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensor_limits" ADD CONSTRAINT fk_sensor_limits_company_id_59 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensor_limits" ADD CONSTRAINT fk_sensor_limits_equipment_id_60 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "condition_readings" ADD CONSTRAINT fk_condition_readings_equipment_id_61 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "condition_readings" ADD CONSTRAINT fk_condition_readings_company_id_62 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "energy_readings" ADD CONSTRAINT fk_energy_readings_equipment_id_63 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "energy_readings" ADD CONSTRAINT fk_energy_readings_company_id_64 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "material_lots" ADD CONSTRAINT fk_material_lots_company_id_65 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batches" ADD CONSTRAINT fk_batches_company_id_66 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batches" ADD CONSTRAINT fk_batches_product_id_67 FOREIGN KEY (product_id) REFERENCES "products"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batches" ADD CONSTRAINT fk_batches_equipment_id_68 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batches" ADD CONSTRAINT fk_batches_mould_id_69 FOREIGN KEY (mould_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batches" ADD CONSTRAINT fk_batches_started_by_70 FOREIGN KEY (started_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batches" ADD CONSTRAINT fk_batches_released_by_71 FOREIGN KEY (released_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batch_materials" ADD CONSTRAINT fk_batch_materials_batch_id_72 FOREIGN KEY (batch_id) REFERENCES "batches"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batch_materials" ADD CONSTRAINT fk_batch_materials_lot_id_73 FOREIGN KEY (lot_id) REFERENCES "material_lots"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_results" ADD CONSTRAINT fk_vision_results_company_id_74 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_results" ADD CONSTRAINT fk_vision_results_equipment_id_75 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "zones" ADD CONSTRAINT fk_zones_company_id_76 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "zones" ADD CONSTRAINT fk_zones_plant_id_77 FOREIGN KEY (plant_id) REFERENCES "plants"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tracked_assets" ADD CONSTRAINT fk_tracked_assets_company_id_78 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tracked_assets" ADD CONSTRAINT fk_tracked_assets_plant_id_79 FOREIGN KEY (plant_id) REFERENCES "plants"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tracked_assets" ADD CONSTRAINT fk_tracked_assets_equipment_id_80 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tracked_assets" ADD CONSTRAINT fk_tracked_assets_home_zone_id_81 FOREIGN KEY (home_zone_id) REFERENCES "zones"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tracked_assets" ADD CONSTRAINT fk_tracked_assets_last_zone_id_82 FOREIGN KEY (last_zone_id) REFERENCES "zones"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asset_sightings" ADD CONSTRAINT fk_asset_sightings_asset_id_83 FOREIGN KEY (asset_id) REFERENCES "tracked_assets"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asset_sightings" ADD CONSTRAINT fk_asset_sightings_zone_id_84 FOREIGN KEY (zone_id) REFERENCES "zones"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "safety_events" ADD CONSTRAINT fk_safety_events_company_id_85 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "safety_events" ADD CONSTRAINT fk_safety_events_plant_id_86 FOREIGN KEY (plant_id) REFERENCES "plants"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "safety_events" ADD CONSTRAINT fk_safety_events_zone_id_87 FOREIGN KEY (zone_id) REFERENCES "zones"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "safety_events" ADD CONSTRAINT fk_safety_events_equipment_id_88 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "safety_events" ADD CONSTRAINT fk_safety_events_reported_by_89 FOREIGN KEY (reported_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "safety_events" ADD CONSTRAINT fk_safety_events_closed_by_90 FOREIGN KEY (closed_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_assistant_messages" ADD CONSTRAINT fk_ticket_assistant_messages_ticket_id_91 FOREIGN KEY (ticket_id) REFERENCES "tickets"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_assistant_messages" ADD CONSTRAINT fk_ticket_assistant_messages_user_id_92 FOREIGN KEY (user_id) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_assistant_messages" ADD CONSTRAINT fk_ticket_assistant_messages_attachment_id_93 FOREIGN KEY (attachment_id) REFERENCES "attachments"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_guides" ADD CONSTRAINT fk_ticket_guides_ticket_id_94 FOREIGN KEY (ticket_id) REFERENCES "tickets"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_guides" ADD CONSTRAINT fk_ticket_guides_created_by_95 FOREIGN KEY (created_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_licences" ADD CONSTRAINT fk_vision_licences_company_id_96 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_nodes" ADD CONSTRAINT fk_vision_nodes_company_id_97 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_nodes" ADD CONSTRAINT fk_vision_nodes_plant_id_98 FOREIGN KEY (plant_id) REFERENCES "plants"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_cameras" ADD CONSTRAINT fk_vision_cameras_company_id_99 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_cameras" ADD CONSTRAINT fk_vision_cameras_plant_id_100 FOREIGN KEY (plant_id) REFERENCES "plants"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_cameras" ADD CONSTRAINT fk_vision_cameras_node_id_101 FOREIGN KEY (node_id) REFERENCES "vision_nodes"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_cameras" ADD CONSTRAINT fk_vision_cameras_zone_id_102 FOREIGN KEY (zone_id) REFERENCES "zones"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_cameras" ADD CONSTRAINT fk_vision_cameras_equipment_id_103 FOREIGN KEY (equipment_id) REFERENCES "equipment"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_assignments" ADD CONSTRAINT fk_vision_assignments_camera_id_104 FOREIGN KEY (camera_id) REFERENCES "vision_cameras"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_assignments" ADD CONSTRAINT fk_vision_assignments_updated_by_105 FOREIGN KEY (updated_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_zones" ADD CONSTRAINT fk_vision_zones_camera_id_106 FOREIGN KEY (camera_id) REFERENCES "vision_cameras"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_media" ADD CONSTRAINT fk_vision_media_company_id_107 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_events" ADD CONSTRAINT fk_vision_events_company_id_108 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_events" ADD CONSTRAINT fk_vision_events_plant_id_109 FOREIGN KEY (plant_id) REFERENCES "plants"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_events" ADD CONSTRAINT fk_vision_events_camera_id_110 FOREIGN KEY (camera_id) REFERENCES "vision_cameras"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_events" ADD CONSTRAINT fk_vision_events_node_id_111 FOREIGN KEY (node_id) REFERENCES "vision_nodes"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_events" ADD CONSTRAINT fk_vision_events_zone_id_112 FOREIGN KEY (zone_id) REFERENCES "vision_zones"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_events" ADD CONSTRAINT fk_vision_events_snapshot_media_id_113 FOREIGN KEY (snapshot_media_id) REFERENCES "vision_media"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_events" ADD CONSTRAINT fk_vision_events_clip_media_id_114 FOREIGN KEY (clip_media_id) REFERENCES "vision_media"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_events" ADD CONSTRAINT fk_vision_events_acknowledged_by_115 FOREIGN KEY (acknowledged_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_events" ADD CONSTRAINT fk_vision_events_resolved_by_116 FOREIGN KEY (resolved_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_stats" ADD CONSTRAINT fk_vision_stats_camera_id_117 FOREIGN KEY (camera_id) REFERENCES "vision_cameras"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trace_units" ADD CONSTRAINT fk_trace_units_company_id_118 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trace_units" ADD CONSTRAINT fk_trace_units_batch_id_119 FOREIGN KEY (batch_id) REFERENCES "batches"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trace_units" ADD CONSTRAINT fk_trace_units_parent_id_120 FOREIGN KEY (parent_id) REFERENCES "trace_units"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trace_units" ADD CONSTRAINT fk_trace_units_created_by_121 FOREIGN KEY (created_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batch_checks" ADD CONSTRAINT fk_batch_checks_company_id_122 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batch_checks" ADD CONSTRAINT fk_batch_checks_batch_id_123 FOREIGN KEY (batch_id) REFERENCES "batches"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batch_checks" ADD CONSTRAINT fk_batch_checks_checked_by_124 FOREIGN KEY (checked_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "process_readings" ADD CONSTRAINT fk_process_readings_batch_id_125 FOREIGN KEY (batch_id) REFERENCES "batches"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "process_deviations" ADD CONSTRAINT fk_process_deviations_company_id_126 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "process_deviations" ADD CONSTRAINT fk_process_deviations_batch_id_127 FOREIGN KEY (batch_id) REFERENCES "batches"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "process_deviations" ADD CONSTRAINT fk_process_deviations_decided_by_128 FOREIGN KEY (decided_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shipments" ADD CONSTRAINT fk_shipments_company_id_129 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shipments" ADD CONSTRAINT fk_shipments_created_by_130 FOREIGN KEY (created_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "field_returns" ADD CONSTRAINT fk_field_returns_company_id_131 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "field_returns" ADD CONSTRAINT fk_field_returns_unit_id_132 FOREIGN KEY (unit_id) REFERENCES "trace_units"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "field_returns" ADD CONSTRAINT fk_field_returns_batch_id_133 FOREIGN KEY (batch_id) REFERENCES "batches"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "field_returns" ADD CONSTRAINT fk_field_returns_created_by_134 FOREIGN KEY (created_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_reviews" ADD CONSTRAINT fk_vision_reviews_event_id_135 FOREIGN KEY (event_id) REFERENCES "vision_events"(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_reviews" ADD CONSTRAINT fk_vision_reviews_company_id_136 FOREIGN KEY (company_id) REFERENCES "companies"(id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vision_reviews" ADD CONSTRAINT fk_vision_reviews_requested_by_137 FOREIGN KEY (requested_by) REFERENCES "users"(id) DEFERRABLE INITIALLY IMMEDIATE;
