-- SQLite's hidden rowid gave these tables their insertion order. PostgreSQL has no such column, so make it explicit.
ALTER TABLE checklist_entries ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE ticket_assistant_messages ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE vision_events ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE INDEX idx_checklist_entries_order ON checklist_entries(ticket_id, seq);
