-- Failure coding lists (ISO 14224 based) become editable master data: a platform admin can add codes and delete
-- ones the business does not use. Tickets keep the code they were recorded with, even after it is deleted.
CREATE TABLE IF NOT EXISTS code_lists (list TEXT NOT NULL, code TEXT NOT NULL, position INTEGER NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY (list,code));
INSERT OR IGNORE INTO code_lists (list,code,position,created_at) VALUES
('failure_categories','mechanical',1,datetime('now')),
('failure_categories','hydraulic',2,datetime('now')),
('failure_categories','pneumatic',3,datetime('now')),
('failure_categories','electrical',4,datetime('now')),
('failure_categories','controls',5,datetime('now')),
('failure_categories','heating',6,datetime('now')),
('failure_categories','cooling',7,datetime('now')),
('failure_categories','tooling',8,datetime('now')),
('failure_categories','material',9,datetime('now')),
('failure_categories','safety',10,datetime('now')),
('failure_categories','other',11,datetime('now')),
('failure_modes','fail_to_start',1,datetime('now')),
('failure_modes','fail_to_stop',2,datetime('now')),
('failure_modes','breakdown',3,datetime('now')),
('failure_modes','low_output',4,datetime('now')),
('failure_modes','erratic_operation',5,datetime('now')),
('failure_modes','abnormal_noise_vibration',6,datetime('now')),
('failure_modes','overheating',7,datetime('now')),
('failure_modes','external_leakage',8,datetime('now')),
('failure_modes','quality_defect',9,datetime('now')),
('failure_modes','structural_damage',10,datetime('now')),
('failure_modes','minor_issue',11,datetime('now')),
('failure_modes','other',12,datetime('now')),
('root_causes','design',1,datetime('now')),
('root_causes','installation',2,datetime('now')),
('root_causes','operation_error',3,datetime('now')),
('root_causes','maintenance_error',4,datetime('now')),
('root_causes','wear_and_ageing',5,datetime('now')),
('root_causes','contamination',6,datetime('now')),
('root_causes','material_or_supply',7,datetime('now')),
('root_causes','external_influence',8,datetime('now')),
('root_causes','unknown',9,datetime('now')),
('actions','replace',1,datetime('now')),
('actions','repair',2,datetime('now')),
('actions','adjust',3,datetime('now')),
('actions','modify',4,datetime('now')),
('actions','clean',5,datetime('now')),
('actions','inspect',6,datetime('now')),
('actions','service',7,datetime('now')),
('actions','overhaul',8,datetime('now')),
('actions','software_update',9,datetime('now')),
('actions','temporary_fix',10,datetime('now'));
