import { t, label, setLocale, formatDateTime, formatDuration, formatNumber, formatTemperature, t as _t } from '/shared/i18n.js';
import { signaturePad } from '/shared/signature.js';
import { scanInput, bindScanInput } from '/shared/scan.js';
import { assetVisual, loadAuthImages, chatText, imageSrc, authImageUrl } from '/shared/media.js';
import { helpView, helpLabel } from '/mobile/help.js';

// Field app for engineers. Works with poor connectivity: assigned work and opened tickets are cached per user,
// changes are queued in IndexedDB with a client action ID (the server deduplicates replays), applied to the cached
// copy immediately so the engineer sees them, and synced in order when the connection returns.
const $=s=>document.querySelector(s),safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={token:sessionStorage.getItem('mc_token'),user:JSON.parse(sessionStorage.getItem('mc_user')||'null'),tickets:[],selected:null,notice:'',error:'',online:navigator.onLine,pending:0,pad:null};
const TRANSITIONS={assigned:['accepted','declined','escalated'],accepted:['in_progress','escalated'],in_progress:['escalated','completed'],escalated:['in_progress','completed']};
const key=(kind,id='')=>`mc_${kind}_${state.user.id}${id?'_'+id:''}`;
const cache={get:(kind,id)=>{try{return JSON.parse(localStorage.getItem(key(kind,id))||'null')}catch{return null}},set:(kind,value,id)=>{try{localStorage.setItem(key(kind,id),JSON.stringify(value))}catch{}},
  clear:()=>Object.keys(localStorage).filter(k=>k.startsWith(`mc_`)&&k.includes(state.user.id)).forEach(k=>localStorage.removeItem(k))};
if(state.user){setLocale(state.user.preferences?.locale);state.tickets=cache.get('tickets')||[];}
const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('mouldcare-field',1);r.onupgradeneeded=()=>r.result.createObjectStore('actions',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function stored(mode,op){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('actions',mode),store=tx.objectStore('actions'),req=op(store);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});}
const queued=async()=>(await stored('readonly',s=>s.getAll())).filter(x=>x.userId===state.user?.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));
async function pending(){state.pending=(await queued()).length;render();}
async function request(path,method='GET',body,actionId){const r=await fetch('/api'+path,{method,headers:{'content-type':'application/json',authorization:`Bearer ${state.token}`,...(actionId?{'x-client-action-id':actionId}:{})},body:body==null?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.error||`${_t('field.http',{status:r.status})}`),{http:true,status:r.status});return data;}
const zone=()=>state.selected?.plant?.timezone;
// Scan at the machine: tickets are raised and closed by scanning the machine's QR label or RFID tag.
const norm=v=>String(v??'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const matches=(asset,code)=>!!asset&&(String(code).trim()===asset.qr_code||(!!asset.rfid_tag&&norm(code)===asset.rfid_tag));
const canRaise=()=>['customer_admin','plant_manager','maintenance','platform_admin','dispatcher'].includes(state.user?.role);
const isDispatchRole=()=>['platform_admin','dispatcher'].includes(state.user?.role);
const scanPolicy=()=>state.cat?.scanPolicy||{raise:'optional',close:'required'};
const badge=(group,s)=>`<span class="badge ${safe(s)}">${safe(label(group,s))}</span>`;

// Optimistic edits applied to the selected ticket (and its cache) while an action waits in the queue.
function applyLocally(edit){if(!state.selected||!edit)return;edit(state.selected);state.selected.queuedChanges=true;cache.set('ticket',state.selected,state.selected.id);}
async function mutate(path,body,edit){
  const item={id:crypto.randomUUID(),userId:state.user.id,path,body,createdAt:new Date().toISOString()};
  const queue=async text=>{await stored('readwrite',s=>s.put(item));applyLocally(edit);state.notice=text;await pending();};
  if(!navigator.onLine)return queue(t('msg.savedOffline'));
  try{const result=await request(path,'POST',body,item.id);state.notice=result?.declined?t('msg.declined'):t('msg.saved');if(result?.declined)state.selected=null;await refresh();return result;}
  catch(e){if(e.http){state.error=e.message;render();return}await queue('Connection dropped. '+t('msg.savedOffline'));}
}
async function sync(){if(!navigator.onLine||!state.token||!state.user)return;for(const item of await queued()){try{await request(item.path,'POST',item.body,item.id);await stored('readwrite',s=>s.delete(item.id));}catch(e){state.error=e.http?`${_t('field.queuedActionNeedsReview',{message:e.message})}`:_t('field.stillOfflineWillRetryLater');break}}await pending();await refresh();}
// Machine data is shared with field engineers only while the job is open, so it is not requested afterwards.
const withTelemetry=async tk=>({...tk,telemetry:tk.status==='completed'?null:await request(`/equipment/${tk.equipment_id}/readings?limit=1`).catch(()=>null)});
async function open(id){state.selected=cache.get('ticket',id)||state.tickets.find(x=>x.id===id);render();try{state.selected=await withTelemetry(await request(`/tickets/${id}`));cache.set('ticket',state.selected,id);render()}catch(e){if(e.http&&[403,404].includes(e.status)){state.selected=null;state.error=e.message;render()}}}
const humanise=v=>{const s=String(v??'').replaceAll('_',' ');return s.charAt(0).toUpperCase()+s.slice(1)};
const options=list=>(list||[]).map(v=>`<option value="${safe(v)}">${safe(humanise(v))}</option>`).join('');
async function loadCatalog(){try{state.cat=await request('/catalog');localStorage.setItem('mc_catalog',JSON.stringify(state.cat))}catch{try{state.cat=JSON.parse(localStorage.getItem('mc_catalog')||'null')}catch{}}}
async function refresh(){
  if(!state.user)return;
  if(!state.cat)await loadCatalog();
  try{state.tickets=await request('/tickets');cache.set('tickets',state.tickets);state.online=true;}catch(e){if(e.http&&e.status===401)return signOut();state.online=false;state.error=_t('field.showingCachedWorkChangesWill');return render();}
  if(state.selected&&!state.pending){try{state.selected=await withTelemetry(await request(`/tickets/${state.selected.id}`));cache.set('ticket',state.selected,state.selected.id);}catch(e){if(e.http&&[403,404].includes(e.status))state.selected=null;}}
  render();
}
function signOut(){stopVision();if(state.user)cache.clear();sessionStorage.removeItem('mc_token');sessionStorage.removeItem('mc_user');Object.assign(state,{token:null,user:null,tickets:[],selected:null,help:null});render();}

function telemetryCard(m){if(!m)return state.selected?.status==='completed'?'':`<div class="section">${t('section.machineData')}</div><div class="card muted">${_t('field.unavailableOfflineOrNotShared')}</div>`;return `<div class="section">${t('section.machineData')}</div><div class="card"><p>${badge('status',m.status)} ${m.lastObservedAt?`<span class="muted">${formatDateTime(m.lastObservedAt,zone())}</span>`:''}</p>${m.metrics?`<p>${_t('field.runningHoursCycles',{value:formatNumber(m.metrics.runningHours.value,1),value2:formatNumber(m.metrics.cycleCount.value),value3:formatTemperature(m.metrics.temperatureC.value,state.user.preferences?.units)})}</p>`:''}${m.activeAlarms.map(a=>`<p>${badge('severity',a.severity)} <b>${safe(a.code)}</b> ${safe(a.message)}</p>`).join('')}</div>`}
function render(){
  if(!state.user){$('#app').innerHTML=`<div class="app"><div class="header"><div class="brand">${_t('field.mould')}<span>${_t('field.care')}</span> ${_t('field.field')}</div><div class="sub">${t('app.field')}</div></div><div class="login card"><h2>${t('action.signIn')}</h2><form id="login" novalidate><label>${t('label.email')}<input name="email" type="email" required autocomplete="username" autocapitalize="none" autocorrect="off" spellcheck="false" inputmode="email" value="${safe(lastEmail())}"></label><label>${t('label.password')}<input name="password" type="password" required autocomplete="current-password"></label><label class="inline"><input type="checkbox" id="show-pw"> ${_t('field.showPassword')}</label><button class="full" id="login-submit">${t('action.signIn')}</button></form>${state.demoAccounts?_t('field.demoAccountsOnThisCopy'):''}${state.error?`<div class="notice error" role="alert">${safe(state.error)}</div>`:''}</div></div>`;$('#login').onsubmit=login;$('#show-pw').onchange=e=>{$('#login [name=password]').type=e.target.checked?'text':'password'};(lastEmail()?$('#login [name=password]'):$('#login [name=email]')).focus();return}
  $('#app').innerHTML=`<div class="app"><div class="header"><div class="row"><div><div class="brand">${_t('field.mould')}<span>${_t('field.care')}</span> ${_t('field.field')}</div><div class="sub">${safe(state.user.name)} · ${safe(label('role',state.user.role))}</div></div><div class="status">${state.online?_t('field.online'):_t('field.offline')} ${state.pending?`<span class="count">${_t('field.queued',{pending:state.pending})}</span>`:''}${state.help?'':_t('field.text')}</div></div></div><div class="content">${visionBanner()}${state.notice?`<div class="notice">${safe(state.notice)}</div>`:''}${state.error?`<div class="notice error">${safe(state.error)}</div>`:''}${state.help?helpView(state.help,{canSeeVision:canSeeVision()}):state.selected?detail():list()}</div><div class="footer"><button class="secondary" id="back">${state.help?'← '+t('action.back'):state.selected?'← '+t('section.assigned'):t('action.signOut')}</button><button id="sync">${t('action.syncNow')}</button></div></div>`;
  $('#help')?.addEventListener('click',()=>{state.help=state.selected?'ticket':'list';render();scrollTo(0,0)});
  $('#back').onclick=()=>{state.notice='';state.error='';if(state.help){state.help=null;render()}else if(state.selected){state.selected=null;render()}else if(state.pending){state.error=_t('field.syncQueuedWorkBeforeSigning');render()}else signOut()};
  $('#sync').onclick=sync;
  document.querySelectorAll('[data-ticket]').forEach(x=>x.onclick=()=>open(x.dataset.ticket));
  document.querySelectorAll('[data-form]').forEach(x=>x.onclick=()=>showForm(x.dataset.form));
  document.querySelectorAll('[data-check]').forEach(x=>x.onclick=()=>{const c=state.selected.checklist.find(i=>i.id===x.dataset.check),done=!c.done;if(c.id.startsWith('local-')){state.notice=_t('field.thisItemSyncsFirstTick');return render()}mutate(`/checklist/${c.id}`,{done,note:c.note},tk=>{tk.checklist.find(i=>i.id===c.id).done=done?1:0})});
  bindVision();
  if(!state.selected&&!state.help)bindScanInput(document,'code',onScan,err=>{state.error=err.message;render()});
  if(state.selected&&navigator.onLine)loadAuthImages(document,state.token);
}
// A scan from the work list: open the machine's open work, or report a breakdown on it. Offline, cached work is
// matched by the machine's label or tag, and a breakdown is queued with the scanned code (the server resolves it).
async function onScan(code){
  state.error='';state.notice='';let asset=null;
  if(navigator.onLine){try{asset=await request(`/equipment/lookup?code=${encodeURIComponent(code)}`)}catch(e){if(e.http){if(e.status===404)throw Error(_t('field.unknownCodeNotTheQr'));if(e.status===403)throw Error(_t('field.thisMachineHasNoWork'));throw e}}}
  if(asset){const work=state.tickets.find(x=>asset.openTicketIds.includes(x.id));if(work)return open(work.id);if(canRaise())return showRaise(code,asset);throw Error(`${_t('field.noOpenWorkFor',{value:asset.assetTag||_t('field.thisMachine')})}`)}
  const cached=state.tickets.filter(x=>x.status!=='completed').find(x=>matches(cache.get('ticket',x.id)?.asset,code));
  if(cached)return open(cached.id);
  if(canRaise())return showRaise(code,null);
  throw Error(_t('field.noCachedOpenWorkFor'));
}
function showRaise(code,asset){state.raise={code,asset};render();showForm('raise');}
function list(){return `${visionList()}<div class="card"><h2>${_t('field.scanAMachine')}</h2><p class="muted">${canRaise()?_t('field.scanItsQrLabelOr'):_t('field.scanItsQrLabelOr2')}</p>${scanInput('code')}</div><div id="form-slot"></div><div class="section">${t('section.assigned')}</div>${state.tickets.length?state.tickets.map(tk=>`<div class="card" data-ticket="${safe(tk.id)}"><div class="row"><h2>${safe(tk.title)}</h2>${badge('priority',tk.priority)}</div><p class="muted">${safe(tk.symptoms)}</p><div class="row"><span>${badge('status',tk.status)}</span><span class="muted">${formatDateTime(tk.created_at)}</span></div></div>`).join(''):`<div class="card empty">${t('msg.noRecords')}</div>`}`}
function detail(){
  const tk=state.selected,work=tk.workLogs||[],check=tk.checklist||[],events=tk.events||[],open=tk.status!=='completed';
  return `<div class="actions">${TRANSITIONS[tk.status]?`<button class="secondary" data-form="status">${t('action.updateStatus')}</button>`:''}${open?`<button data-form="work">${t('action.logWork')}</button><button class="secondary" data-form="check">${t('action.checklist')}</button>`:''}<button class="secondary" data-form="part">${t('action.requestPart')}</button><button class="secondary" data-form="ai">${_t('field.askAiAssistant')}</button><button class="secondary" data-form="guide">${tk.priority==='critical'?_t('field.repairGuideVr'):_t('field.repairGuide')}</button><button class="secondary" data-form="photo">${_t('field.addPhoto')}</button><button class="secondary" data-form="safety">${_t('field.reportSafetyConcern')}</button>${tk.status==='completed'&&!tk.signoff?`<button data-form="signoff">${t('action.signoff')}</button>`:''}</div><div id="form-slot"></div>
  ${tk.queuedChanges&&!state.notice?`<div class="notice">${t('msg.savedOffline')}</div>`:''}<div class="card"><div class="row"><h2>${safe(tk.title)}</h2>${badge('priority',tk.priority)}</div><p>${badge('status',tk.status)} · ${safe(tk.error_codes||'—')}</p><div class="asset-row">${assetVisual(tk.asset||{},64)}<p><b>${t('label.asset')}</b><br>${safe(tk.asset?.make||'')} ${safe(tk.asset?.model||'')} · ${safe(tk.asset?.serial_number||'')}<br>${safe(tk.plant?.name||'')} · ${safe(tk.asset?.location||'')}</p></div>${tk.safety_issue?_t('field.safetyIssueReportedSecureThe'):''}<p><b>${_t('field.breakdown')}</b><br>${safe(humanise(tk.failure_category||'—'))} · ${safe(humanise(tk.machine_state||'—'))}${tk.occurred_at?` ${_t('field.since',{occurred_at:formatDateTime(tk.occurred_at,zone())})}`:''}</p><p><b>${t('label.symptoms')}</b><br>${safe(tk.symptoms)}</p><p><b>${t('label.impact')}</b><br>${safe(tk.production_impact)}</p><p class="muted">${t('label.downtime')}: ${formatDuration(tk.downtime_minutes)}${tk.responseDueAt?` · ${t('label.responseDue')}: ${formatDateTime(tk.responseDueAt,zone())}`:''}</p>${tk.coverage?`<p class="muted">${safe(tk.coverage.title)} · ${t('label.exclusions')}: ${safe(tk.coverage.exclusions)}</p>`:''}</div>${telemetryCard(tk.telemetry)}
  <div class="section">${t('section.checklist')}</div><div class="card">${check.length?check.map(c=>`<div class="check ${c.done?'done':''}" ${open?`${_t('field.dataCheckRoleButton',{id:safe(c.id)})}`:''}><span class="box">${c.done?'☑':'☐'}</span><span>${safe(c.item)}${c.note?` <span class="muted">${safe(c.note)}</span>`:''}</span></div>`).join(''):t('msg.noRecords')}</div>
  <div class="section">${t('section.work')}</div><div class="card">${work.length?work.map(w=>`<p>${safe(w.description)}<br><span class="muted">${formatDuration(w.minutes)} · ${safe(w.parts_used)}</span></p>`).join(''):t('msg.noRecords')}</div>
  ${tk.signoff?`<div class="card">${safe(t('msg.signedBy',{name:tk.signoff.signer_name,date:formatDateTime(tk.signoff.signed_at,zone())}))}</div>`:''}
  <div class="section">${t('section.activity')}</div><div class="card">${events.length?events.map(x=>`<p>${badge('status',x.event_type)}<br><span class="muted">${formatDateTime(x.created_at,zone())} · ${safe(x.detail)}</span></p>`).join(''):t('msg.noRecords')}</div>`;
}
// Breakdown assistant and repair guide: need a connection (answers come from the server), so they are not queued.
async function showAssistant(kind){
  const tk=state.selected,slot=$('#form-slot');
  if(!navigator.onLine){slot.innerHTML='<div class="card muted">The assistant and the guide need a connection.</div>';return}
  slot.innerHTML='<div class="card muted">Loading…</div>';
  try{if(kind==='ai')renderChat(await request(`/tickets/${tk.id}/assistant`));else renderGuide(await request(`/tickets/${tk.id}/guide`))}
  catch(e){slot.innerHTML=`<div class="card notice error">${safe(e.message)}</div>`}
}
function renderChat(a){
  const tk=state.selected,slot=$('#form-slot');if(!slot)return;
  slot.innerHTML=`<div class="card"><h2>${_t('field.breakdownAssistant')}</h2>${!a.enabled?_t('field.theAiAssistantIsNot'):`<p class="muted">${_t('field.aiAnswersCanBeWrong')}</p><div class="chat" id="chat">${a.messages.map(m=>`<div class="msg ${m.role}"><div class="who">${m.role==='user'?safe(m.user_name):_t('field.assistant')} · ${formatDateTime(m.created_at,zone())}</div>${m.attachment_id?`<img class="chat-photo" data-auth-src="/api/attachments/${safe(m.attachment_id)}" alt="${_t('field.photoSentWithTheQuestion')}">`:''}${m.role==='assistant'?chatText(m.content):`<p>${safe(m.content)}</p>`}</div>`).join('')||_t('field.askAboutThisBreakdownOr')}</div>${a.canAsk&&tk.status!=='completed'?`<div class="quick-asks">${[_t('field.whatShouldIDoNext'),_t('field.mostLikelyCause'),_t('field.whichSparePartsMightBe')].map(q=>`<button type="button" class="secondary" data-ask="${safe(q)}">${safe(q)}</button>`).join('')}</div><form id="ai-form"><textarea name="message" maxlength="2000" placeholder="${_t('field.eGWhatShouldI')}"></textarea><label>${_t('field.addAPhotoOptional')}<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" capture="environment"></label><button class="full">${_t('field.ask')}</button></form>`:''}`}</div>`;
  const chat=$('#chat');if(chat)chat.scrollTop=chat.scrollHeight;loadAuthImages(slot,state.token);
  const f=$('#ai-form');if(!f)return;
  slot.querySelectorAll('[data-ask]').forEach(c=>c.onclick=()=>{f.message.value=c.dataset.ask;f.requestSubmit()});
  f.onsubmit=async e=>{e.preventDefault();const message=f.message.value.trim(),file=f.photo.files[0],b=f.querySelector('button.full');
    if(!message&&!file){f.message.focus();return}if(file?.size>5*1024*1024){slot.insertAdjacentHTML('afterbegin','<div class="notice error">The photo is larger than 5 MB.</div>');return}
    b.disabled=true;b.textContent=_t('field.thinkingUpToAMinute');
    try{const photo=file?{filename:file.name,mime:file.type,base64:await toBase64(file)}:undefined;renderChat(await request(`/tickets/${tk.id}/assistant`,'POST',{message,...(photo?{photo}:{})}))}catch(err){b.disabled=false;b.textContent=_t('field.ask');state.error=err.message;$('#form-slot').insertAdjacentHTML('afterbegin',`<div class="notice error">${safe(err.message)}</div>`)}};
}
function renderGuide(g){
  const tk=state.selected,slot=$('#form-slot');if(!slot)return;const x=g.guide;
  slot.innerHTML=`<div class="card"><h2>${_t('field.repairGuide')} <span class="badge">${g.source==='ai'?_t('field.ai'):_t('field.standard')}</span></h2>${tk.priority==='critical'?_t('field.openVrGuideCriticalBreakdown'):''}${x.summary?`<p>${safe(x.summary)}</p>`:''}${x.hazards?.length?`<div class="notice error"><b>${_t('field.hazards')}</b><ul>${x.hazards.map(h=>`<li>${safe(h)}</li>`).join('')}</ul></div>`:''}${x.ppe?.length?`<p><b>${_t('field.ppe')}</b> ${x.ppe.map(safe).join(' · ')}</p>`:''}<ol class="guide-steps">${x.steps.map(st=>`<li><b>${safe(st.title)}</b><br>${safe(st.instruction)}${st.check?`<br><span class="muted">✓ ${safe(st.check)}</span>`:''}</li>`).join('')}</ol>${tk.status!=='completed'?`<button class="secondary full" id="guide-write">${g.aiEnabled?(g.source==='ai'?_t('field.rewriteWithAi'):_t('field.writeWithAi')):_t('field.updateGuide')}</button>`:''}</div>`;
  if($('#vr-open'))$('#vr-open').onclick=()=>openVr(x).catch(e=>{state.error=e.message;render()});
  if($('#guide-write'))$('#guide-write').onclick=async e=>{const b=e.target;b.disabled=true;b.textContent=g.aiEnabled?_t('field.writingUpToAMinute'):_t('field.updating');try{renderGuide(await request(`/tickets/${tk.id}/guide`,'POST',{}))}catch(err){b.disabled=false;b.textContent=_t('field.tryAgain');slot.insertAdjacentHTML('afterbegin',`<div class="notice error">${safe(err.message)}</div>`)}};
}
async function openVr(guide){
  const tk=state.selected,a=tk.asset||{},image=imageSrc(a)?await authImageUrl(imageSrc(a),state.token):null;
  const {openVrGuide}=await import('/shared/vr.js');
  await openVrGuide({title:tk.title,critical:tk.priority==='critical',guide,image,machine:{name:`${a.asset_tag?a.asset_tag+' · ':''}${a.make||''} ${a.model||''}`,detail:`${tk.plant?.name||''} · ${a.location||''}`,report:`${tk.symptoms}${tk.error_codes?`${_t('field.codes',{error_codes:tk.error_codes})}`:''}${tk.safety_issue?'\n⚠ Safety issue reported':''}`}});
}
function showForm(kind){
  if(kind==='ai'||kind==='guide')return showAssistant(kind);
  const tk=state.selected,assignee=['engineer','provider_admin','provider_engineer'].includes(state.user.role);let html='';
  if(kind==='status')html=`<label>${t('label.status')}<select name="status">${TRANSITIONS[tk.status].filter(s=>s!=='declined'||assignee).map(x=>`<option value="${x}">${safe(label('status',x))}</option>`).join('')}</select></label><label>${t('label.downtime')} (${t('label.minutes')})<input name="downtimeMinutes" type="number" min="0" value="${tk.downtime_minutes||''}" placeholder="${tk.machine_state==='stopped'?_t('field.leaveEmptyTimeSinceFailure'):''}"></label><div id="closeout" hidden><div class="section">${_t('field.closeOutIso14224')}</div><label>${_t('field.failureMode')}<select name="failureMode"><option value="">${_t('field.select')}</option>${options(state.cat?.failureModes)}</select></label><label>${_t('field.rootCause')}<select name="rootCause"><option value="">${_t('field.select')}</option>${options(state.cat?.rootCauses)}</select></label><label>${_t('field.actionTaken')}<select name="actionTaken"><option value="">${_t('field.select')}</option>${options(state.cat?.actions)}</select></label><label for="f-scanCode">${_t('field.scanTheMachineToClose',{value:safe(tk.asset?.asset_tag||''),value2:scanPolicy().close==='required'&&!isDispatchRole()?' *':''})}</label>${scanInput('scanCode')}<small class="help" id="close-scan" role="status">${scanPolicy().close==='required'?_t('field.scanItsQrLabelOr3'):_t('field.optionalRecordsThatTheJob')}</small>${scanPolicy().close==='required'&&isDispatchRole()?_t('field.reasonForClosingWithoutA'):''}</div><label>${t('label.note')} <span class="muted">${t('msg.noteRequired')}</span><textarea name="note"></textarea></label>`;
  if(kind==='work')html=`<label>${_t('field.workPerformed')}<textarea name="description" required></textarea></label><label>${t('label.minutes')}<input name="minutes" type="number" min="1" required></label><label>${_t('field.partsUsed')}<input name="partsUsed"></label>`;
  if(kind==='check')html=`<label>${_t('field.inspectionItem')}<input name="item" required></label><label>${t('label.note')}<input name="note"></label>`;
  if(kind==='part')html=`<label>${_t('field.partNumber')}<input name="partNumber" required></label><label>${_t('field.manufacturer')}<input name="manufacturer"></label><label>${_t('field.description')}<input name="item" required></label><label>${_t('field.quantity')}<input name="quantity" type="number" min="1" value="1" required></label><label>${_t('field.unit')}<select name="unit">${(state.cat?.partUnits||['pcs']).map(u=>`<option value="${safe(u)}">${safe(u)}</option>`).join('')}</select></label><label>${_t('field.urgency')}<select name="urgency">${options(state.cat?.partUrgency||['normal','urgent','breakdown'])}</select></label>`;
  if(kind==='raise'){const r=state.raise;html=`<p>${r.asset?`<b>${safe(r.asset.assetTag||'')}</b> ${safe(r.asset.make)} ${safe(r.asset.model)}<br><span class="muted">${_t('field.identifiedByIts',{value:safe(r.asset.location||''),value2:r.asset.scannedVia==='rfid'?_t('field.rfidTag'):_t('field.qrLabel')})}</span>`:_t('field.offlineTheMachineIsIdentified')}</p><input type="hidden" name="scanCode" value="${safe(r.code)}"><label>${_t('field.shortDescription')}<input name="title" required maxlength="160" placeholder="${_t('field.eGHydraulicPressureDrops')}"></label><label>${t('label.symptoms')} *<textarea name="symptoms" required placeholder="${_t('field.whatYouSeeHearOr')}"></textarea></label><label>${t('label.errorCodes')}<input name="errorCodes"></label><label>${_t('field.failureCategory')}<select name="failureCategory" required><option value="">${_t('field.select')}</option>${options(state.cat?.failureCategories)}</select></label><label>${_t('field.machineState')}<select name="machineState" required><option value="">${_t('field.select')}</option>${options(state.cat?.machineStates)}</select></label><label>${t('label.priority')} *<select name="priority">${['critical','high','medium','low'].map(p=>`<option value="${p}" ${p==='high'?'selected':''}>${safe(label('priority',p))}</option>`).join('')}</select></label><label>${_t('field.isAnyoneAtRiskOr')}<select name="safetyIssue" required><option value="">${_t('field.select')}</option><option value="no">${_t('field.no')}</option><option value="yes">${_t('field.yesPriorityBecomesCritical')}</option></select></label><label>${t('label.impact')} *<textarea name="productionImpact" required placeholder="${_t('field.eGLineStoppedScrap')}"></textarea></label><label>${_t('field.photosOfTheBreakdown')}<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" multiple></label><p class="muted">${_t('field.optionalTheFailedPartLeaks')}</p><label>${_t('field.failureStarted')}<select name="startedAgo">${[[0,_t('field.justNow')],[15,'15 minutes ago'],[30,'30 minutes ago'],[60,'1 hour ago'],[120,'2 hours ago'],[240,'4 hours ago'],[480,'8 hours ago']].map(([m,l])=>`<option value="${m}">${l}</option>`).join('')}</select></label>`}
  if(kind==='photo')html='<label>Photo evidence<input name="file" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" required></label>';
  if(kind==='safety')html=`<p class="muted">${_t('field.reportAHazardNearMiss')}</p><label>${_t('field.whatHappened')}<select name="eventType" required><option value="">${_t('field.select')}</option>${Object.keys(state.cat?.safetyEvents||{near_miss:1,unsafe_condition:1,unsafe_act:1,first_aid:1,injury:1}).map(k=>`<option value="${safe(k)}">${safe(humanise(k))}</option>`).join('')}</select></label><label>${_t('field.description')}<textarea name="description" required placeholder="${_t('field.whatHappenedAndWhatCould')}"></textarea></label>`;
  if(kind==='signoff')html=`<label>${t('label.signerName')}<input name="signerName" required></label><label>${t('label.signature')}</label><canvas class="signature" id="sig"></canvas><button class="secondary" type="button" id="clear-sig">${t('action.clear')}</button>`;
  $('#form-slot').innerHTML=`<div class="card"><h2>${safe({status:t('action.updateStatus'),work:t('action.logWork'),check:t('action.checklist'),part:t('action.requestPart'),photo:_t('field.addPhoto'),safety:_t('field.reportSafetyConcern2'),signoff:t('action.signoff'),raise:_t('field.reportBreakdown')}[kind])}</h2><form id="action-form">${html}<button class="full">${t('action.save')}</button></form></div>`;
  if(kind==='signoff'){state.pad=signaturePad($('#sig'));$('#clear-sig').onclick=()=>state.pad.clear();}
  if(kind==='status'){const note=$('#close-scan'),input=$('#action-form [name=scanCode]'),show=(text,ok)=>{note.textContent=text;note.className=`${_t('field.help',{value:ok?'scan-ok':'scan-bad'})}`};
    // Checked on the device against the ticket's machine (works offline); the server checks again when it syncs.
    bindScanInput($('#form-slot'),'scanCode',async code=>{if(matches(tk.asset,code))return show(`${_t('field.confirmed',{value:tk.asset.asset_tag||_t('field.machine')})}`,true);if(!navigator.onLine)return show(_t('field.willBeCheckedWhenThis'),true);const a=await request(`/equipment/lookup?code=${encodeURIComponent(code)}`).catch(()=>null);if(a?.id!==tk.equipment_id)throw Error(`${_t('field.notScanTheLabelOr',{value:tk.asset?.asset_tag||_t('field.thisMachine')})}`);show(`${_t('field.confirmed',{value:a.assetTag||_t('field.machine')})}`,true)},e=>{input.value='';show(e.message,false)});}
  if(kind==='status'){const sel=$('#action-form [name=status]'),box=$('#closeout');const sync=()=>{const done=sel.value==='completed';box.hidden=!done;box.querySelectorAll('select').forEach(x=>x.required=done)};sel.onchange=sync;sync();}
  $('#action-form').onsubmit=e=>submit(e,kind);
}
async function submit(e,kind){
  e.preventDefault();const f=new FormData(e.target),v=Object.fromEntries(f),tk=state.selected,now=new Date().toISOString();let path,body,edit;
  if(kind==='status'){if(['declined','escalated'].includes(v.status)&&!v.note.trim()){state.error=t('msg.noteRequired');return render()}if(v.status==='completed'&&(!v.failureMode||!v.rootCause||!v.actionTaken)){state.error=_t('field.toCompleteChooseTheFailure');return render()}const scan=v.status!=='completed'?{}:v.scanCode?{scanCode:v.scanCode}:v.scanOverrideReason?.trim()?{scanOverrideReason:v.scanOverrideReason.trim()}:{};if(v.status==='completed'&&scanPolicy().close==='required'&&!Object.keys(scan).length){state.error=isDispatchRole()?_t('field.scanTheMachineOrGive'):_t('field.scanTheMachineSQr');return render()}path=`/tickets/${tk.id}/status`;body={status:v.status,note:v.note,...(v.downtimeMinutes!==''?{downtimeMinutes:Number(v.downtimeMinutes)}:{}),...(v.status==='completed'?{failureMode:v.failureMode,rootCause:v.rootCause,actionTaken:v.actionTaken,...scan}:{})};edit=x=>{x.status=v.status==='declined'?'open':v.status;if(body.downtimeMinutes!=null)x.downtime_minutes=body.downtimeMinutes;if(v.status==='completed')Object.assign(x,{failure_mode:v.failureMode,root_cause:v.rootCause,action_taken:v.actionTaken});x.events=[...(x.events||[]),{event_type:v.status,detail:v.note,created_at:now}]}}
  if(kind==='work'){path=`/tickets/${tk.id}/work-logs`;body={description:v.description,minutes:Number(v.minutes),partsUsed:v.partsUsed};edit=x=>{x.workLogs=[...(x.workLogs||[]),{description:v.description,minutes:body.minutes,parts_used:v.partsUsed}]}}
  if(kind==='check'){path=`/tickets/${tk.id}/checklist`;body={item:v.item,note:v.note,done:false};edit=x=>{x.checklist=[...(x.checklist||[]),{id:'local-'+crypto.randomUUID(),item:v.item,note:v.note,done:0}]}}
  if(kind==='part'){path=`/tickets/${tk.id}/parts`;body={item:v.item,partNumber:v.partNumber,manufacturer:v.manufacturer,quantity:Number(v.quantity),unit:v.unit,urgency:v.urgency}}
  if(kind==='raise'){const r=state.raise;path='/tickets';body={...(r.asset?{equipmentId:r.asset.id}:{}),scanCode:v.scanCode,title:v.title,symptoms:v.symptoms,errorCodes:v.errorCodes,failureCategory:v.failureCategory,machineState:v.machineState,priority:v.priority,safetyIssue:v.safetyIssue==='yes',productionImpact:v.productionImpact,occurredAt:new Date(Date.now()-Number(v.startedAgo)*60000).toISOString()};state.raise=null}
  if(kind==='photo'){const file=f.get('file');if(file.size>5*1024*1024){state.error=_t('field.photoExceeds5Mb');return render()}const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});path='/attachments';body={entityType:'ticket',entityId:tk.id,kind:'evidence',filename:file.name,mime:file.type,base64}}
  if(kind==='safety'){path='/safety/events';body={plantId:tk.plant_id,equipmentId:tk.equipment_id,eventType:v.eventType,description:v.description,occurredAt:now}}
  if(kind==='signoff'){if(!state.pad||state.pad.isEmpty()){state.error=t('msg.signFirst');return render()}path=`/tickets/${tk.id}/signoff`;body={signerName:v.signerName,signatureBase64:state.pad.toBase64()};edit=x=>{x.signoff={signer_name:v.signerName,signed_at:now,method:'on_site'}};state.pad=null}
  state.error='';$('#form-slot').innerHTML='';const result=await mutate(path,body,edit);
  if(kind==='raise'){const photos=f.getAll('photos').filter(x=>x?.size);
    if(result?.id){for(const p of photos){if(p.size>5*1024*1024){state.error=`${_t('field.isLargerThan5Mb',{name:p.name})}`;continue}try{await request('/attachments','POST',{entityType:'ticket',entityId:result.id,kind:'photo',filename:p.name,mime:p.type,base64:await toBase64(p)})}catch(e){state.error=`${p.name}: ${e.message}`}}await open(result.id)}
    else if(photos.length){state.notice=_t('field.breakdownQueuedPhotosNeedA');render()}}
}
const toBase64=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});
// ---------- Vision alarms (security and EHS on the move) ----------
// Open fire, intrusion and – for people with those duties – PPE and quality alarms, polled every 5 s while online.
// A new critical alarm vibrates the phone and sounds a tone.
const userZone=()=>state.user?.preferences?.timezone;
const canSeeVision=()=>['customer_admin','plant_manager','maintenance','platform_admin','dispatcher'].includes(state.user?.role);
const vType=t=>({ppe_violation:_t('field.ppeViolation'),fire:_t('field.fire'),smoke:_t('field.smoke'),intrusion_person:_t('field.personInRestrictedArea'),intrusion_vehicle:_t('field.vehicleInRestrictedArea'),defect:_t('field.defect')})[t]||humanise(t);
const vIcon=a=>a.type==='fire'||a.type==='smoke'?'🔥':a.module==='intrusion'?'🚫':a.module==='ppe'?'⛑':'⚠';
const vDetail=a=>a.module==='ppe'?`${_t('field.missing',{value:(a.detail?.missing||[]).join(', ')})}`:a.zoneName?a.zoneName:a.module==='quality'?humanise(a.detail?.defect||''):'';
let visionTimer=null,visionSeen=new Set(),tone=null;
function alertPerson(){try{navigator.vibrate?.([400,150,400,150,400])}catch{}try{tone??=new AudioContext();const o=tone.createOscillator(),g=tone.createGain();o.frequency.value=880;g.gain.value=0.2;o.connect(g);g.connect(tone.destination);o.start();o.stop(tone.currentTime+0.7)}catch{}}
async function pollVision(){if(!state.user||!canSeeVision()||!navigator.onLine)return;try{const list=await request('/vision/alarms');const fresh=list.some(a=>a.severity==='critical'&&!visionSeen.has(a.id));list.forEach(a=>visionSeen.add(a.id));const changed=JSON.stringify(list.map(a=>a.id))!==JSON.stringify((state.valarms||[]).map(a=>a.id));state.valarms=list;if(fresh)alertPerson();if(changed&&!document.querySelector('#action-form'))render()}catch{}}
function startVision(){if(visionTimer||!canSeeVision())return;pollVision();visionTimer=setInterval(pollVision,5000)}
function stopVision(){clearInterval(visionTimer);visionTimer=null;visionSeen=new Set();state.valarms=[];state.vEvent=null}
function visionBanner(){const top=(state.valarms||[]).find(a=>a.severity==='critical');if(!top)return'';return `<div class="valarm" role="alert"><span class="va-i">${vIcon(top)}</span><div><b>${safe(vType(top.type))}</b><br><span>${safe(top.cameraName)}${top.location?` · ${safe(top.location)}`:''} · ${formatDateTime(top.occurredAt,userZone())}</span></div><div class="va-b"><button data-vview="${safe(top.id)}">${_t('field.view')}</button><button data-vack="${safe(top.id)}">${_t('field.acknowledge')}</button></div></div>`}
function visionList(){const list=state.valarms||[];if(!list.length&&!state.vEvent)return'';return `${state.vEvent?visionEvent():''}${list.length?`<div class="section">${_t('field.visionAlarms')}</div>${list.map(a=>`<div class="card valarm-card ${a.severity}" data-vview="${safe(a.id)}" role="button"><div class="row"><b>${vIcon(a)} ${safe(vType(a.type))}</b><span class="badge ${a.severity}">${safe(a.severity)}</span></div><p class="muted">${safe(a.cameraName)}${a.location?` · ${safe(a.location)}`:''}<br>${safe(vDetail(a))} · ${formatDateTime(a.occurredAt,userZone())}</p></div>`).join('')}`:''}`}
function visionEvent(){const e=state.vEvent;return `<div class="card vevent-card"><div class="row"><h2>${vIcon(e)} ${safe(vType(e.type))}</h2><span class="badge ${e.severity}">${safe(e.severity)}</span></div>${e.snapshotMediaId?`<div class="vframe"><img data-vmedia="${safe(e.snapshotMediaId)}" alt="${_t('field.snapshotAtDetection')}">${(e.boxes||[]).map(b=>`<span class="bbox ${b.ok?'ok':''}" style="left:${b.x*100}%;top:${b.y*100}%;width:${b.w*100}%;height:${b.h*100}%"><em>${safe(b.label||'')}</em></span>`).join('')}</div>`:''}${e.clipMediaId?`<video controls playsinline data-vclip="${safe(e.clipMediaId)}"></video>`:''}<p>${safe(e.cameraName)}${e.location?` · ${safe(e.location)}`:''}<br>${safe(vDetail(e))}<br><span class="muted">${formatDateTime(e.occurredAt,userZone())} · ${safe(humanise(e.status))}</span></p><div class="actions">${e.status==='open'?`<button data-vack="${safe(e.id)}">${_t('field.acknowledge')}</button>`:''}<button class="secondary" id="vclose">${_t('field.close')}</button></div></div>`}
function bindVision(){
  document.querySelectorAll('[data-vview]').forEach(x=>x.onclick=async()=>{try{state.vEvent=await request(`/vision/events/${x.dataset.vview}`);state.selected=null;render();window.scrollTo(0,0)}catch(e){state.error=e.message;render()}});
  document.querySelectorAll('[data-vack]').forEach(x=>x.onclick=async()=>{try{await request(`/vision/events/${x.dataset.vack}/acknowledge`,'POST',{});state.notice=_t('field.alarmAcknowledged');if(state.vEvent?.id===x.dataset.vack)state.vEvent=await request(`/vision/events/${x.dataset.vack}`);await pollVision();render()}catch(e){state.error=e.message;render()}});
  if($('#vclose'))$('#vclose').onclick=()=>{state.vEvent=null;render()};
  document.querySelectorAll('img[data-vmedia]:not([src])').forEach(async img=>{const u=await authImageUrl(`/api/vision/media/${img.dataset.vmedia}`,state.token);if(u)img.src=u});
  document.querySelectorAll('video[data-vclip]:not([src])').forEach(async v=>{const u=await authImageUrl(`/api/vision/media/${v.dataset.vclip}`,state.token);if(u)v.src=u});
}
function lastEmail(){try{return localStorage.getItem('pmp_last_email')||''}catch{return ''}}
async function login(e){e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.email=String(v.email||'').trim();if(!v.email||!v.password){state.error=!v.email?_t('field.enterYourEmailAddress'):_t('field.enterYourPassword');return render()}const submitBtn=$('#login-submit');submitBtn.disabled=true;submitBtn.textContent=_t('field.signingIn');try{try{localStorage.setItem('pmp_last_email',v.email)}catch{}const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(v)}),data=await r.json();if(!r.ok)throw Error(data.error);state.token=data.token;state.user=data.user;setLocale(data.user.preferences.locale);sessionStorage.setItem('mc_token',data.token);sessionStorage.setItem('mc_user',JSON.stringify(data.user));state.error='';if(data.user.mustChangePassword)state.notice=t('msg.mustChange')+' (web workspace → Account)';state.tickets=cache.get('tickets')||[];await pending();await sync();startVision()}catch(err){state.error=err.message;render()}}
window.addEventListener('online',()=>{state.online=true;sync()});window.addEventListener('offline',()=>{state.online=false;render()});
if('serviceWorker' in navigator)navigator.serviceWorker.register('/mobile/sw.js').catch(()=>{});
if(state.user){pending().then(refresh);startVision()}else fetch('/api/config').then(r=>r.json()).then(c=>{state.demoAccounts=!!c.demoAccounts}).catch(()=>{}).finally(render);
