import { db, id, now, one, run } from './db.js';
import { hashPassword } from './security.js';

const stamp=now(), daysAgo=d=>new Date(Date.now()-d*86400000).toISOString();
function company(key,name,currency,timezone,locale,country,contact,email,phone) { run('INSERT INTO companies (id,name,timezone,currency,units,locale,created_at,country,contact_name,contact_email,contact_phone) VALUES (?,?,?,?,?,?,?,?,?,?,?)',key,name,timezone,currency,'metric',locale,stamp,country,contact,email,phone); }
function provider(key,name,areas,skills,country,contact,email,phone,certs) { run('INSERT INTO providers (id,name,approved,service_areas,skills,created_at,country,contact_name,contact_email,contact_phone,insurance_expiry,certifications) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',key,name,1,JSON.stringify(areas),JSON.stringify(skills),stamp,country,contact,email,phone,'2027-06-30T00:00:00.000Z',certs); }
function user(key,name,email,role,companyId=null,providerId=null,areas=[],skills=[],phone='',title='') { run('INSERT INTO users (id,company_id,provider_id,name,email,password_hash,role,active,service_areas,skills,created_at,phone,job_title) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',key,companyId,providerId,name,email,hashPassword('DemoPass123!'),role,1,JSON.stringify(areas),JSON.stringify(skills),stamp,phone,title); }
function equipment(key,companyId,plantId,type,make,model,serial,location,tag,criticality,year,specs) { run('INSERT INTO equipment (id,company_id,plant_id,machine_type,make,model,serial_number,location,qr_code,created_at,asset_tag,criticality,status,year_built,specs) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',key,companyId,plantId,type,make,model,serial,location,`MC:${key}`,stamp,tag,criticality,'in_service',year,JSON.stringify(specs)); }
function ticket(t) { run('INSERT INTO tickets (id,company_id,plant_id,equipment_id,title,priority,symptoms,error_codes,production_impact,status,assigned_user_id,assigned_provider_id,created_by,created_at,first_response_at,completed_at,downtime_minutes,failure_category,machine_state,safety_issue,occurred_at,failure_mode,root_cause,action_taken) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',t.id,t.company,t.plant,t.equipment,t.title,t.priority,t.symptoms,t.codes,t.impact,t.status,t.user??null,t.provider??null,t.by,t.created,t.response??null,t.completed??null,t.downtime,t.category,t.state,0,t.occurred??t.created,t.mode??null,t.cause??null,t.action??null); }
const event=(ticketId,actor,type,detail,at=stamp)=>run('INSERT INTO ticket_events (id,ticket_id,actor_id,event_type,detail,created_at) VALUES (?,?,?,?,?,?)',id(),ticketId,actor,type,detail,at);

if (one('SELECT 1 FROM companies LIMIT 1')) { console.log('Seed already present'); process.exit(0); }
db.exec('BEGIN IMMEDIATE');
try {
  for (const [code,name] of [['US-MW','United States – Midwest'],['DE-NW','Germany – North-West'],['IN-S','India – South']]) run('INSERT OR IGNORE INTO service_areas (code,name,created_at) VALUES (?,?,?)',code,name,stamp);
  company('c-acme','Acme Plastics','USD','America/Chicago','en','US','Sam Acme','acme@demo.test','+1 312 555 0100'); company('c-nova','Nova Polymers','EUR','Europe/Berlin','de','DE','Nora Nova','nova@demo.test','+49 221 555 0100');
  provider('p-atlas','Atlas Field Service',['US-MW'],['injection','mould','auxiliary'],'US','Avery Atlas','atlas-admin@demo.test','+1 312 555 0200','ISO 9001; OEM-certified Arburg service');
  provider('p-euro','EuroTech Service',['DE-NW'],['blow','extrusion','auxiliary'],'DE','Emil Euro','euro@demo.test','+49 221 555 0200','ISO 9001');
  user('u-admin','Platform Admin','admin@demo.test','platform_admin'); user('u-dispatch','Maya Dispatch','dispatch@demo.test','dispatcher',null,null,[],[],'+1 312 555 0300','Service dispatcher');
  user('u-engineer','Alex Engineer','engineer@demo.test','engineer',null,null,['US-MW'],['injection','mould'],'+1 312 555 0301','Field service engineer');
  user('u-acme','Sam Acme','acme@demo.test','customer_admin','c-acme',null,[],[],'+1 312 555 0100','Maintenance manager'); user('u-acme-maint','Lee Maintenance','maint@demo.test','maintenance','c-acme',null,[],[],'','Maintenance technician');
  user('u-nova','Nora Nova','nova@demo.test','customer_admin','c-nova',null,[],[],'+49 221 555 0100','Leiterin Instandhaltung');
  user('u-atlas-admin','Avery Atlas','atlas-admin@demo.test','provider_admin',null,'p-atlas',['US-MW'],['injection','mould'],'+1 312 555 0200','Service manager');
  user('u-atlas','Ari Atlas','atlas@demo.test','provider_engineer',null,'p-atlas',['US-MW'],['injection','mould'],'+1 312 555 0201','Service engineer');
  user('u-euro','Emil Euro','euro@demo.test','provider_engineer',null,'p-euro',['DE-NW'],['blow','extrusion'],'+49 221 555 0201','Servicetechniker');
  run('INSERT INTO plants (id,company_id,name,address,country,service_area,timezone,created_at,operating_pattern) VALUES (?,?,?,?,?,?,?,?,?)','plant-a','c-acme','Chicago Plant','1200 Industrial Way, Chicago, IL','US','US-MW','America/Chicago',stamp,'24x5');
  run('INSERT INTO plants (id,company_id,name,address,country,service_area,timezone,created_at,operating_pattern) VALUES (?,?,?,?,?,?,?,?,?)','plant-n','c-nova','Cologne Plant','Werkstrasse 8, 50667 Köln','DE','DE-NW','Europe/Berlin',stamp,'24x7');
  equipment('eq-a','c-acme','plant-a','injection','Arburg','Allrounder 570','ARB-570-001','Bay 4','IMM-04','A',2019,{clampForceKn:2000,shotVolumeCm3:442,screwDiameterMm:50,driveType:'hydraulic',controller:'Selogica'});
  equipment('eq-b','c-acme','plant-a','mould','Husky','Hot Runner 24','HSK-2409','Tool Room','MLD-24','B',2021,{mouldNumber:'M-2409',cavities:24,hotRunner:'yes',hotRunnerZones:26,shotCount:1842000,pmIntervalShots:250000,steelGrade:'1.2343'});
  equipment('eq-n','c-nova','plant-n','extrusion','Coperion','ZSK 58','COP-58-811','Line 2','EXT-02','A',2017,{lineType:'compounding',screwConfig:'twin',screwDiameterMm:58,ldRatio:44,outputKgH:400});
  equipment('eq-c','c-acme','plant-a','auxiliary','Motan','Luxor CA 120','MOT-120-77','Bay 4 mezzanine','AUX-DRY-01','B',2019,{auxType:'dryer',capacity:'120 L hopper',linkedEquipmentId:'eq-a'});
  run('INSERT INTO contracts (id,company_id,title,starts_at,renews_at,commitments,exclusions,status,created_at,response_hours,contract_number,coverage_hours,restore_hours,visits_per_year,notice_days) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)','contract-a','c-acme','Annual care 2026','2026-01-01T00:00:00.000Z','2027-01-01T00:00:00.000Z','4 preventive visits; 8-hour response','Consumables and tooling','active',stamp,8,'AMC-2026-001','8x5',48,4,60);
  run('INSERT INTO contract_equipment (contract_id,equipment_id) VALUES (?,?)','contract-a','eq-a');
  run('INSERT INTO visits (id,contract_id,company_id,equipment_id,due_at,status,notes) VALUES (?,?,?,?,?,?,?)','visit-a','contract-a','c-acme','eq-a','2026-11-15T14:00:00.000Z','scheduled','Quarterly inspection');
  run('INSERT INTO contracts (id,company_id,title,starts_at,renews_at,commitments,exclusions,status,created_at,response_hours,contract_number,coverage_hours,restore_hours,visits_per_year,notice_days) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)','contract-n','c-nova','Wartungsvertrag Linie 2','2025-12-01T00:00:00.000Z','2026-12-01T00:00:00.000Z','2 inspections per year; 4-hour response','Screw and barrel wear parts','active',stamp,4,'WV-2025-017','24x7',24,2,90);
  run('INSERT INTO contract_equipment (contract_id,equipment_id) VALUES (?,?)','contract-n','eq-n');
  run('INSERT INTO visits (id,contract_id,company_id,equipment_id,due_at,status,notes) VALUES (?,?,?,?,?,?,?)','visit-n','contract-n','c-nova','eq-n','2026-10-20T07:00:00.000Z','scheduled','Half-year inspection');
  ticket({id:'ticket-a',company:'c-acme',plant:'plant-a',equipment:'eq-a',title:'Hydraulic pressure drops',priority:'high',symptoms:'Pressure falls after warm-up',codes:'E-204',impact:'Line stopped',status:'assigned',user:'u-engineer',by:'u-acme',created:stamp,downtime:120,category:'hydraulic',state:'stopped'});
  ticket({id:'ticket-n',company:'c-nova',plant:'plant-n',equipment:'eq-n',title:'Extruder temperature alarm',priority:'critical',symptoms:'Zone 3 overheats',codes:'T-302',impact:'Reduced output',status:'assigned',provider:'p-euro',by:'u-nova',created:stamp,downtime:45,category:'heating',state:'reduced_output'});
  // History: an earlier, completed occurrence of the same fault on eq-a, so repeat faults, MTTR and downtime have data.
  ticket({id:'ticket-a-old',company:'c-acme',plant:'plant-a',equipment:'eq-a',title:'Hydraulic pressure low at start-up',priority:'medium',symptoms:'Pressure slow to build',codes:'E-204',impact:'Delayed start',status:'completed',user:'u-engineer',by:'u-acme-maint',created:daysAgo(20),occurred:daysAgo(20.05),response:daysAgo(19.9),completed:daysAgo(19.7),downtime:180,category:'hydraulic',state:'stopped',mode:'low_output',cause:'wear_and_ageing',action:'replace'});
  run('INSERT INTO work_logs (id,ticket_id,user_id,description,minutes,parts_used,created_at) VALUES (?,?,?,?,?,?,?)','wl-old','ticket-a-old','u-engineer','Replaced worn pressure relief valve seal; pressure stable at setpoint',150,'Relief valve seal kit',daysAgo(19.7));
  run("INSERT INTO signoffs (ticket_id,customer_user_id,signer_name,signed_at,method) VALUES (?,?,?,?,'portal')",'ticket-a-old','u-acme-maint','Lee Maintenance',daysAgo(19.6));
  for (const [type,detail,at] of [['assigned','Assigned to Alex Engineer',daysAgo(20)],['accepted','',daysAgo(19.9)],['completed','Seal replaced',daysAgo(19.7)]]) event('ticket-a-old','u-dispatch',type,detail,at);
  event('ticket-a','u-dispatch','assigned','Assigned to Alex Engineer'); event('ticket-n','u-dispatch','assigned','Assigned to EuroTech Service');
  run('INSERT INTO parts_requests (id,company_id,ticket_id,item,quantity,status,created_at,updated_at,part_number,unit,urgency,manufacturer) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)','part-a','c-acme','ticket-a','Pressure relief valve assembly',1,'quoted',stamp,stamp,'ARB-PRV-570-02','pcs','breakdown','Arburg');
  run('INSERT INTO quotations (id,request_id,company_id,amount_minor,currency,lead_days,status,created_at,valid_until) VALUES (?,?,?,?,?,?,?,?,?)','quote-a','part-a','c-acme',48500,'USD',3,'pending',stamp,new Date(Date.now()+30*86400000).toISOString().slice(0,10)+'T00:00:00.000Z');
  run('INSERT INTO device_mappings (id,external_device_id,company_id,equipment_id,created_at) VALUES (?,?,?,?,?)','map-a','demo-device-a','c-acme','eq-a',stamp);
  run('INSERT INTO device_mappings (id,external_device_id,company_id,equipment_id,created_at) VALUES (?,?,?,?,?)','map-n','demo-device-n','c-nova','eq-n',stamp);
  db.exec('COMMIT'); console.log('Seeded two customers, two providers, equipment, contracts, tickets and history. Password: DemoPass123!');
} catch(e) { db.exec('ROLLBACK'); throw e; }
